FROM ghcr.io/cirruslabs/flutter:latest AS build

WORKDIR /app

COPY ./pubspec.lock ./pubspec.yaml /app/

RUN flutter pub get

RUN flutter clean

RUN flutter pub get

COPY . .

ENTRYPOINT ["flutter", "build", "web", "--wasm", "--release"]