services:
    database:
        build:
            context: ./database
        container_name: course_recommender_database
        expose:
            - "${DB_PORT}"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - TZ='UTC+5'
            - PGTZ='UTC+5'
        volumes:
            - CRD:/var/lib/postgresql/data
            - ./database/entrypoint:/docker-entrypoint-initdb.d:ro
        networks:
            - course-recommender-network
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: ./backend
        container_name: course_recommender_backend
        expose:
            - "${BACKEND_PORT}"
        depends_on:
            database:
                condition: service_healthy
        environment:
            - user=${POSTGRES_USER}
            - password=${POSTGRES_PASSWORD}
            - host=${DB_HOST}
            - dbport=${DB_PORT}
            - dbname=${POSTGRES_DB}
            - sslmode=disable
            - BACKEND_PORT=${BACKEND_PORT}
        networks:
            - course-recommender-network
        restart: unless-stopped

    nginx:
        build:
            context: ./nginx
        container_name: course_recommender_nginx
        depends_on:
            - backend
        expose:
            - "${NGINX_HTTP_PORT}"
            - "${NGINX_HTTPS_PORT}"
        environment:
            - BACKEND_PORT=${BACKEND_PORT}
            - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
            - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
        volumes:
            - ./frontend/build/web:/usr/share/nginx/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/myapp.conf.template:/etc/nginx/templates/myapp.conf.template:ro
            - ./nginx/ssl:/etc/ssl:ro
            - ./nginx/log:/var/log/nginx:rw
        networks:
            - course-recommender-network
        restart: unless-stopped

    cloudflared:
        image: cloudflare/cloudflared:latest
        depends_on:
            - nginx
        command: tunnel --no-autoupdate --protocol http2 run
        environment:
            - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
        networks:
            - course-recommender-network
        restart: unless-stopped

volumes:
    CRD:

networks:
    course-recommender-network:
        driver: bridge
