services:
    database:
        build:
            context: ./database
        container_name: course_recommender_database
        expose:
            - "${DB_PORT}"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - TZ='UTC+5'
            - PGTZ='UTC+5'
        volumes:
            - CRD:/var/lib/postgresql/data
            - ./database/enterypoint:/docker-entrypoint-initdb.d:ro
        networks:
            - course-recommender-network
        restart: unless-stopped

    backend:
        build:
            context: ./backend
        container_name: course_recommender_backend
        expose:
            - "${BACKEND_PORT}"
        depends_on:
            - database
        environment:
            - user=${POSTGRES_USER}
            - password=${POSTGRES_PASSWORD}
            - host=${DB_HOST}
            - dbport=${DB_PORT}
            - dbname=${POSTGRES_DB}
            - sslmode=disable
            - BACKEND_PORT=${BACKEND_PORT}
        networks:
            - course-recommender-network
        restart: unless-stopped

    envoy:
        build:
            context: ./envoy
        container_name: course_recommender_envoy
        depends_on:
            - backend
        expose:
            - "${ENVOY_PORT}"
            - "${ENVOY_ADMIN_PORT}"
        environment:
            - BACKEND_PORT=${BACKEND_PORT}
            - ENVOY_PORT=${ENVOY_PORT}
            - ENVOY_ADMIN_PORT=${ENVOY_ADMIN_PORT}
        networks:
            - course-recommender-network
        restart: unless-stopped

    nginx:
        build:
            context: ./nginx
        container_name: course_recommender_nginx
        depends_on:
            - envoy
        environment:
            - BACKEND_PORT=${BACKEND_PORT}
            - ENVOY_PORT=${ENVOY_PORT}
            - NGINX_PORT=${NGINX_PORT}
        ports:
            - "${NGINX_PORT}:${NGINX_PORT}"
        volumes:
            - ./frontend/build/web:/usr/share/nginx/html:ro
            - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
        networks:
            - course-recommender-network
        restart: unless-stopped

volumes:
    CRD:

networks:
    course-recommender-network:
        driver: bridge
