INSERT INTO degree_type(degree_name)
VALUES ('accounting and finance'),
    ('business administration'),
    ('electrical engineering'),
    ('anthropology and sociology'),
    ('biology'),
    ('chemistry'),
    ('humanities and social sciences'),
    ('computer science'),
    ('management science'),
    ('economics'),
    ('education'),
    ('engineering'),
    ('english'),
    ('environmental studies'),
    ('law'),
    ('gender studies'),
    ('history'),
    ('global south languages'),
    ('mathematics'),
    ('physics'),
    ('political science'),
    ('science'),
    ('swimming');