INSERT INTO
    course (course_name, difficulty)
VALUES
    ('principles of financial accounting', 1),
    ('principles of management accounting', 1),
    (
        'theory and concepts of accounting - islamic perspective',
        2
    ),
    ('corporate financial reporting i', 2),
    ('applied financial analysis', 4),
    ('governance, risk and compliance', 4),
    ('introduction to finance and accounting', 2),
    ('financial management and accounting', 5),
    ('analytics in accounting and control', 6),
    ('foundations of ai', 5),
    ('mathematics for ai', 5),
    ('introduction to cultural anthropology', 1),
    ('anthropology of social media', 2),
    ('modernity as a way of life', 3),
    (
        'putting social science to the test: mixed-methods approaches to lahore’s developmental challenges',
        4
    ),
    ('children of abraham', 4),
    ('caste in south asia and beyond', 4),
    ('introductory biology', 1),
    ('molecular biology', 2),
    ('genetics', 2),
    ('methods in cell and molecular biology', 3),
    ('cell biology', 3),
    ('computational biology ii', 3),
    ('seminars in biology', 4),
    (
        'critical thinking, scientific writing and ethics',
        4
    ),
    ('introduction to computational neuroscience', 4),
    ('advanced methods in biology', 5),
    ('biophysical techniques', 5),
    ('advanced molecular and cell biology', 5),
    (
        'molecular mechanisms of bacterial pathagenesis',
        5
    ),
    ('rna biology', 5),
    ('evolution', 5),
    ('computational biology', 5),
    ('physical chemistry', 2),
    ('principles of chemical engineering', 2),
    ('particle science and engineering', 2),
    ('chemical engineering lab ii', 3),
    ('air pollution', 3),
    ('separation processes', 3),
    ('math methods in chemical engineering ii', 3),
    ('heat and mass transfer', 3),
    ('chemical process design', 4),
    ('chemical engineering lab - v', 4),
    ('chemical engineering lab - vi', 4),
    (
        'renewable energy: fundamentals, applications, and economics',
        4
    ),
    ('chemical process safety', 4),
    ('transport processes in the environment', 7),
    ('principles of chemistry', 1),
    ('molecular symmetry i', 2),
    ('fundamentals of organic chemistry', 2),
    ('quantum chemistry', 3),
    ('inorganic chemistry i', 3),
    ('chemistry of the organic functional groups', 3),
    ('analytical chemistry i', 3),
    ('physical chemistry lab', 4),
    ('organic chemistry lab ii', 4),
    ('characterization techniques for materials', 5),
    ('advanced inorganic chemistry i', 5),
    ('advanced organic chemistry i', 5),
    ('chemistry of biomolecule', 5),
    ('selected topics in inorganic chemistry', 7),
    ('selected topics in organic chemistry', 7),
    ('engaging with texts and contexts', 1),
    ('mechanics of fiction', 2),
    ('urdu afsana', 2),
    (
        'fountain of the sun: rumi''s masnavi and divan',
        2
    ),
    ('the critical lens: the art of filmmaking', 2),
    ('introduction to illustrative storytelling', 2),
    ('aag ka darya: a close reading', 3),
    ('film and screen studies research seminar', 3),
    ('the craft of translation', 3),
    ('life writing and the multilingual self', 3),
    ('computational problem solving', 1),
    ('introduction to programming', 2),
    ('data structures', 2),
    ('discrete mathematics', 2),
    ('fundamentals of computer systems', 2),
    ('algorithms', 3),
    ('principles and techniques of data science', 3),
    ('databases', 3),
    ('e-government', 3),
    ('operating systems', 3),
    ('digital system design', 4),
    ('digital system design lab', 4),
    ('computer vision fundamentals', 4),
    ('deep learning', 4),
    ('machine learning', 4),
    ('computer graphics', 4),
    ('coding for careers', 4),
    ('cloud development', 4),
    ('applied probability', 5),
    ('game design and development', 5),
    ('distributed systems', 5),
    ('hardware design for iot security', 5),
    ('computer architecture', 6),
    (
        'topics in large language models: systems, applications and impacts',
        6
    ),
    ('multi-agent systems', 6),
    ('topics in computer and network security', 6),
    ('computer and problem solving', 1),
    ('probability and statistics', 2),
    ('introduction to management science', 2),
    ('operations management', 2),
    (
        'qualitative and quantitative methods in business',
        3
    ),
    ('decision analysis', 3),
    ('optimization methods in management science', 3),
    ('decision behaviour', 3),
    ('risk management process', 3),
    ('project management', 3),
    ('supply chain and logistics management', 3),
    ('business analytics', 4),
    ('applied statistics', 7),
    ('seminar in supply chain analysis', 8),
    (
        'seminar in technology and innovation management',
        8
    ),
    ('principles of economics', 1),
    ('principles of microeconomics', 1),
    ('principles of macroeconomics', 1),
    ('intermediate microeconomics', 2),
    ('intermediate macroeconomics', 2),
    ('statistics and data analysis', 2),
    ('introduction to game theory', 2),
    ('development economics', 2),
    ('sectors and policy in development', 2),
    ('principles of finance', 2),
    ('mathematical applications in economics', 2),
    ('economic history of south asia', 3),
    ('econometrics', 3),
    ('gender economics', 3),
    ('agriculture and food policy', 3),
    (
        'money and monetary policy: applications to pakistan',
        3
    ),
    ('economics of investment and finance', 3),
    ('economics of education', 4),
    ('gender and the labor market', 4),
    ('computational macroeconomics', 4),
    ('econometrics ii', 4),
    ('development economics theory', 4),
    ('issues in economic policy', 4),
    ('philosophy and economics', 4),
    ('microeconomic analysis', 5),
    ('econometrics and research methodology i', 5),
    ('topics in mathematical method for economists', 5),
    ('critical debates in education', 2),
    (
        'education and international development - concepts, theories, and issues',
        2
    ),
    (
        'trauma-informed education systems: creating cultures of support and change',
        2
    ),
    ('education, schools and violence', 2),
    ('gender media and education', 2),
    (
        'designing immersive learning experiences: student-centered instructional skills training',
        3
    ),
    ('socio emotional learning', 3),
    (
        'inclusive pedagogy: rethinking teaching, learning and assessment',
        3
    ),
    ('the (instructional) core and how to work it', 3),
    ('education and conflict', 3),
    ('mobile lives: im/migration and education', 3),
    ('behavior analysis for effective teaching', 4),
    (
        'interdisciplinary theoretical perspectives on education',
        5
    ),
    ('the arts and education', 5),
    (
        'education and happiness: combining learning with hope and positivity',
        5
    ),
    (
        'enhancing inclusion: exploring autism and intellectual disability',
        5
    ),
    ('leadership: the politics of change', 5),
    ('research methods', 5),
    ('observing schools', 5),
    ('practicum proseminar', 6),
    ('academic writing', 6),
    ('professional learning in education', 5),
    (
        'arts-based research: exploring creative practices in educational inquiry',
        6
    ),
    ('impact evaluation methods in education', 6),
    ('sophomore design studio', 2),
    ('engineering models', 2),
    ('circuits i', 2),
    ('microcontroller and interfacing', 3),
    ('microcontroller and interfacing lab', 3),
    ('electromagnetic fields and waves', 3),
    ('devices and electronics', 3),
    ('devices and electronics lab', 3),
    ('communication systems', 3),
    ('communication systems lab', 3),
    ('power electronics', 4),
    ('power electronics lab', 4),
    ('power systems protection and stability', 4),
    ('electrodynamics', 5),
    ('advanced topics in machine learning', 5),
    ('vlsi design for artificial intelligence', 5),
    (
        'data analysis, design of experiments and physics informed ml',
        5
    ),
    ('local solutions for energy access', 5),
    ('renewable energy systems', 5),
    ('smart grid: technology and applications', 5),
    (
        'understanding financial accounting: making more authoritative decisions',
        5
    ),
    ('corporate finance', 5),
    ('marketing management', 5),
    ('problem solving and decision making', 5),
    ('business law', 5),
    ('venture creation', 6),
    ('design and measurement lab', 1),
    ('introduction to literature in english', 1),
    ('writing south asia', 1),
    ('introduction to humour writing', 1),
    ('comics scholarship and graphic narrative', 2),
    (
        'rethinking the politics of harem in literature: women, islam, and gendered spaces',
        2
    ),
    (
        'text and tech: digital approaches to the humanities',
        2
    ),
    (
        '''the empire writes back'': diaspora fiction in europe',
        3
    ),
    ('african literature: women writing back', 3),
    ('introduction to environmental studies', 1),
    ('disasters', 1),
    ('methods in environmental studies', 2),
    ('environmentalism and development', 3),
    ('intermediate finance', 2),
    (
        'fintech revolution: market disruption and emerging opportunities',
        2
    ),
    ('actuarial sciences and insurance', 3),
    ('fundamentals of actuarial mathematics i', 3),
    ('applied corporate finance', 4),
    ('financial modelling', 4),
    ('islamic banking and finance', 4),
    ('portfolio management', 4),
    ('mathematical modeling', 7),
    ('seminar in islamic and corporate finance', 8),
    (
        'seminar in financial intermediation and regualatory framework',
        8
    ),
    (
        'financial statement analysis and value creation',
        5
    ),
    ('chinese language for beginners (hsk level 1)', 1),
    ('writing from the trial', 2),
    ('introduction to gender and sexuality studies', 2),
    (
        'master narratives: minding gender and media gaps',
        2
    ),
    ('feminist theory', 3),
    ('east asian history', 1),
    ('the world since 1453', 1),
    ('making of modern afghanistan', 2),
    ('a brief history of evil', 2),
    (
        'conceptual understanding of borders and borderlands studies',
        2
    ),
    ('19th century sikh wall paintings in punjab', 3),
    ('civil war in the 20th century', 3),
    ('the cold war', 3),
    (
        'the atomic age: control, confrontation, disaster',
        3
    ),
    ('islamic historiography: an introduction', 3),
    (
        'walking in the city: mapping everyday life in lahore',
        4
    ),
    ('healthcare operations management', 6),
    ('arabic for quran', 1),
    ('introduction to balochi language', 1),
    ('introduction to punjabi language', 1),
    ('introduction to arabic language', 1),
    ('introduction to persian language', 1),
    ('sindhi for non-sindhi speakers', 1),
    ('pashto for non-native speakers', 1),
    ('pashto: intermediate proficiency', 2),
    ('the art of reading and writing punjabi', 2),
    ('sindhi: intermediate proficiency', 2),
    (
        'contemporary persian for social and professional use',
        2
    ),
    ('enhancing urdu reading and writing skills', 2),
    ('civil procedure', 4),
    ('introduction to pakistan legal system', 1),
    ('contracts', 2),
    ('torts', 2),
    ('criminal law', 2),
    (
        'legal practice i: legal writing and research methods',
        2
    ),
    ('advanced writing from the trial', 3),
    (
        'international relations and international law: chinese perspectives',
        3
    ),
    ('public international law', 3),
    ('human rights', 3),
    ('marxist theories of law', 4),
    (
        'crime, law and finance: wonders of white color crime in pakistan!',
        4
    ),
    ('parliamentary power play', 4),
    ('the jurisprudence of extractivism', 4),
    (
        'business and human rights: a critical legal perspective from the south',
        4
    ),
    ('criminal procedure', 4),
    ('legal practice ii: legal instruments', 4),
    ('prison paralegal clinic', 4),
    ('pre-calculus', 1),
    ('calculus i', 1),
    ('calculus i (honours)', 1),
    ('calculus ii', 1),
    ('linear algebra with differential equations', 1),
    ('introduction to formal mathematics', 2),
    ('introduction to differential equations', 2),
    ('linear algebra ii', 2),
    ('probability', 2),
    ('complex variables', 3),
    ('introduction to analysis ii', 3),
    ('operations research i', 3),
    ('symmetry methods for differential equations', 4),
    ('numerical linear algebra', 4),
    (
        'symmetry methods, conservation laws and exact solutions for differential equations',
        5
    ),
    ('advanced algebra', 5),
    ('probability and statistical analysis', 5),
    ('advanced numerical linear algebra', 5),
    ('operational research i', 5),
    ('organizational behaviour', 5),
    ('managerial communication', 5),
    ('financial accounting i', 5),
    ('financial accounting ii', 5),
    ('finance fundamentals', 5),
    ('statistical analysis for management', 5),
    ('experiential learning i', 5),
    ('islamic banking', 6),
    ('investments', 6),
    ('entrepreneurial finance', 6),
    ('supply chain management', 6),
    ('blockchain and cryptocurrency', 6),
    ('data visualization', 6),
    ('digital marketing', 6),
    ('retail management', 6),
    ('consumer analytics', 6),
    ('channel management', 6),
    ('brand management', 6),
    ('sales force management', 6),
    ('human resource management', 6),
    ('managing workplace diversity', 6),
    (
        'understanding and managing self-identity in contemporary organizations',
        6
    ),
    ('negotiation skills', 6),
    ('corporate entrepreneurship', 6),
    ('business development and economy', 6),
    ('family business', 6),
    ('managing in the information age', 6),
    ('financial markets', 6),
    (
        'the fintech revolution: concept, conversation and challenges',
        6
    ),
    (
        'strategic management of non-profit enterprises',
        6
    ),
    ('introduction to business economics', 2),
    ('business economics', 5),
    ('economic theory', 7),
    ('principles of management', 1),
    ('business communication', 2),
    (
        'business ethics and corporate social responsibility',
        2
    ),
    ('public administration', 2),
    ('public financial management', 2),
    ('logic and critical thinking', 2),
    ('introduction to management', 2),
    ('introduction to policy analysis', 2),
    ('governance system of pakistan', 2),
    (
        'contemporary social policy issues in pakistan',
        2
    ),
    ('fundamentals of hospitality management', 2),
    ('internet governance and technology policy', 3),
    ('business, government, and society', 3),
    ('strategic business management', 4),
    ('entrepreneurship', 4),
    ('philosophy of administrative sciences', 7),
    ('seminar in strategic management', 8),
    ('principles of marketing', 2),
    ('introduction to marketing', 2),
    ('using new media technologies in marketing', 3),
    ('integrated marketing communications', 3),
    ('consumer behaviour', 3),
    ('marketing models', 3),
    ('data analytics for new product development', 3),
    ('organizations and leadership', 5),
    ('applications of psychology in management', 7),
    ('seminar in human resource management', 8),
    ('introduction to logic', 1),
    ('introduction to philosophy ii', 2),
    ('contemporary moral problems', 2),
    ('mechanics', 1),
    ('electricity and magnetism', 2),
    ('quantum mechanics i', 2),
    (
        'mathematical methods in physics and engineering i',
        2
    ),
    ('experimental physics lab ii', 3),
    ('classical mechanics', 3),
    ('statistical mechanics', 3),
    ('relativistic electrodynamics', 4),
    ('graduate physics lab', 5),
    ('advanced statistical mechanics', 5),
    ('quantum algorithms', 5),
    ('advanced quantum mechanics', 5),
    ('magnetism: theory and experiment', 6),
    ('comparative politics', 3),
    ('introduction to political science', 1),
    (
        'introduction to politics in developing countries',
        1
    ),
    ('introduction to political theory', 2),
    (
        'decolonizing democracy: lessons from the global south',
        2
    ),
    ('women and political theory', 2),
    ('making modern afghanistan', 2),
    ('political islam: ideology and politics', 3),
    (
        'qualitative research methods in political science',
        3
    ),
    ('marxism and the modern world', 3),
    ('theories of ir', 3),
    ('terrorism as political action', 3),
    ('political leadership', 4),
    ('diplomacy in international relations', 4),
    (
        'introduction to psychology and human behavior',
        1
    ),
    ('theories of learning', 2),
    ('perception', 2),
    ('psychopathology', 2),
    ('social psychology', 3),
    ('life span development', 3),
    ('what is religion', 2),
    (
        'introduction to quranic and modern standard arabic',
        2
    ),
    (
        'scientific imagination and the religious mind',
        2
    ),
    ('religion, conflict, and peace building', 2),
    ('religion and existentialism', 3),
    ('what is ""islamic"" history?', 3),
    (
        'experience and interpretation in muslim feminist scriptural discourse',
        3
    ),
    ('stem teaching in the ai era', 5),
    ('operations and supply chain strategy', 6),
    ('introduction to sociology', 1),
    ('classical sociological theory', 3),
    ('quantitative research methods', 3),
    ('the informal economy', 3),
    ('social science and the post-secular age', 3),
    ('introduction to writing', 1),
    ('writing and communication', 1),
    ('islamic studies', 1),
    ('pakistan studies: culture and heritage', 1),
    (
        'sur, tal aur rag: foundations of south asian music',
        1
    ),
    ('introduction to kathak', 1),
    ('applied statistics for humanities', 1),
    ('media writing', 2),
    ('professional communication skills', 3),
    ('first year tutorial', 1),
    ('swimming for beginners', 1),
    (
        'strength training and conditioning for beginners',
        1
    ),
    ('basketball for beginners', 1),
    ('walk, jog and stretch for fitness', 1);