// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: course_tag.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The CourseTag message, representing the many-to-many relationship
// between courses and tags.
type CourseTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TagId         int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseTag) Reset() {
	*x = CourseTag{}
	mi := &file_course_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseTag) ProtoMessage() {}

func (x *CourseTag) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseTag.ProtoReflect.Descriptor instead.
func (*CourseTag) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{0}
}

func (x *CourseTag) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CourseTag) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

// Request to create a new course-tag association.
type CreateCourseTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TagId         int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseTagRequest) Reset() {
	*x = CreateCourseTagRequest{}
	mi := &file_course_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseTagRequest) ProtoMessage() {}

func (x *CreateCourseTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseTagRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseTagRequest) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseTagRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CreateCourseTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

// Response containing the newly created course-tag association.
type CreateCourseTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseTag     *CourseTag             `protobuf:"bytes,1,opt,name=course_tag,json=courseTag,proto3" json:"course_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseTagResponse) Reset() {
	*x = CreateCourseTagResponse{}
	mi := &file_course_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseTagResponse) ProtoMessage() {}

func (x *CreateCourseTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseTagResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseTagResponse) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseTagResponse) GetCourseTag() *CourseTag {
	if x != nil {
		return x.CourseTag
	}
	return nil
}

// Request to get all tags for a specific course.
type GetTagsByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsByCourseIdRequest) Reset() {
	*x = GetTagsByCourseIdRequest{}
	mi := &file_course_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsByCourseIdRequest) ProtoMessage() {}

func (x *GetTagsByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*GetTagsByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{3}
}

func (x *GetTagsByCourseIdRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response containing a list of tags for a specific course.
type GetTagsByCourseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsByCourseIdResponse) Reset() {
	*x = GetTagsByCourseIdResponse{}
	mi := &file_course_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsByCourseIdResponse) ProtoMessage() {}

func (x *GetTagsByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*GetTagsByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{4}
}

func (x *GetTagsByCourseIdResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Request to get all courses for a specific tag.
type GetCoursesByTagIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesByTagIdRequest) Reset() {
	*x = GetCoursesByTagIdRequest{}
	mi := &file_course_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesByTagIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesByTagIdRequest) ProtoMessage() {}

func (x *GetCoursesByTagIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesByTagIdRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesByTagIdRequest) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{5}
}

func (x *GetCoursesByTagIdRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

// Response containing a list of courses for a specific tag.
type GetCoursesByTagIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesByTagIdResponse) Reset() {
	*x = GetCoursesByTagIdResponse{}
	mi := &file_course_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesByTagIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesByTagIdResponse) ProtoMessage() {}

func (x *GetCoursesByTagIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesByTagIdResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesByTagIdResponse) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{6}
}

func (x *GetCoursesByTagIdResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

// Request to delete a course-tag association.
type DeleteCourseTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TagId         int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseTagRequest) Reset() {
	*x = DeleteCourseTagRequest{}
	mi := &file_course_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseTagRequest) ProtoMessage() {}

func (x *DeleteCourseTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseTagRequest) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCourseTagRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *DeleteCourseTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

// Response indicating whether the deletion was successful.
type DeleteCourseTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseTagResponse) Reset() {
	*x = DeleteCourseTagResponse{}
	mi := &file_course_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseTagResponse) ProtoMessage() {}

func (x *DeleteCourseTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseTagResponse) Descriptor() ([]byte, []int) {
	return file_course_tag_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCourseTagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_course_tag_proto protoreflect.FileDescriptor

const file_course_tag_proto_rawDesc = "" +
	"\n" +
	"\x10course_tag.proto\x12\x12course_recommender\x1a\fcourse.proto\x1a\ttag.proto\"?\n" +
	"\tCourseTag\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\"L\n" +
	"\x16CreateCourseTagRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\"W\n" +
	"\x17CreateCourseTagResponse\x12<\n" +
	"\n" +
	"course_tag\x18\x01 \x01(\v2\x1d.course_recommender.CourseTagR\tcourseTag\"7\n" +
	"\x18GetTagsByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"H\n" +
	"\x19GetTagsByCourseIdResponse\x12+\n" +
	"\x04tags\x18\x01 \x03(\v2\x17.course_recommender.TagR\x04tags\"1\n" +
	"\x18GetCoursesByTagIdRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x03R\x05tagId\"Q\n" +
	"\x19GetCoursesByTagIdResponse\x124\n" +
	"\acourses\x18\x01 \x03(\v2\x1a.course_recommender.CourseR\acourses\"L\n" +
	"\x16DeleteCourseTagRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\"3\n" +
	"\x17DeleteCourseTagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xce\x03\n" +
	"\x10CourseTagService\x12j\n" +
	"\x0fCreateCourseTag\x12*.course_recommender.CreateCourseTagRequest\x1a+.course_recommender.CreateCourseTagResponse\x12p\n" +
	"\x11GetTagsByCourseId\x12,.course_recommender.GetTagsByCourseIdRequest\x1a-.course_recommender.GetTagsByCourseIdResponse\x12p\n" +
	"\x11GetCoursesByTagId\x12,.course_recommender.GetCoursesByTagIdRequest\x1a-.course_recommender.GetCoursesByTagIdResponse\x12j\n" +
	"\x0fDeleteCourseTag\x12*.course_recommender.DeleteCourseTagRequest\x1a+.course_recommender.DeleteCourseTagResponseB\aZ\x05./apib\x06proto3"

var (
	file_course_tag_proto_rawDescOnce sync.Once
	file_course_tag_proto_rawDescData []byte
)

func file_course_tag_proto_rawDescGZIP() []byte {
	file_course_tag_proto_rawDescOnce.Do(func() {
		file_course_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_tag_proto_rawDesc), len(file_course_tag_proto_rawDesc)))
	})
	return file_course_tag_proto_rawDescData
}

var file_course_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_course_tag_proto_goTypes = []any{
	(*CourseTag)(nil),                 // 0: course_recommender.CourseTag
	(*CreateCourseTagRequest)(nil),    // 1: course_recommender.CreateCourseTagRequest
	(*CreateCourseTagResponse)(nil),   // 2: course_recommender.CreateCourseTagResponse
	(*GetTagsByCourseIdRequest)(nil),  // 3: course_recommender.GetTagsByCourseIdRequest
	(*GetTagsByCourseIdResponse)(nil), // 4: course_recommender.GetTagsByCourseIdResponse
	(*GetCoursesByTagIdRequest)(nil),  // 5: course_recommender.GetCoursesByTagIdRequest
	(*GetCoursesByTagIdResponse)(nil), // 6: course_recommender.GetCoursesByTagIdResponse
	(*DeleteCourseTagRequest)(nil),    // 7: course_recommender.DeleteCourseTagRequest
	(*DeleteCourseTagResponse)(nil),   // 8: course_recommender.DeleteCourseTagResponse
	(*Tag)(nil),                       // 9: course_recommender.Tag
	(*Course)(nil),                    // 10: course_recommender.Course
}
var file_course_tag_proto_depIdxs = []int32{
	0,  // 0: course_recommender.CreateCourseTagResponse.course_tag:type_name -> course_recommender.CourseTag
	9,  // 1: course_recommender.GetTagsByCourseIdResponse.tags:type_name -> course_recommender.Tag
	10, // 2: course_recommender.GetCoursesByTagIdResponse.courses:type_name -> course_recommender.Course
	1,  // 3: course_recommender.CourseTagService.CreateCourseTag:input_type -> course_recommender.CreateCourseTagRequest
	3,  // 4: course_recommender.CourseTagService.GetTagsByCourseId:input_type -> course_recommender.GetTagsByCourseIdRequest
	5,  // 5: course_recommender.CourseTagService.GetCoursesByTagId:input_type -> course_recommender.GetCoursesByTagIdRequest
	7,  // 6: course_recommender.CourseTagService.DeleteCourseTag:input_type -> course_recommender.DeleteCourseTagRequest
	2,  // 7: course_recommender.CourseTagService.CreateCourseTag:output_type -> course_recommender.CreateCourseTagResponse
	4,  // 8: course_recommender.CourseTagService.GetTagsByCourseId:output_type -> course_recommender.GetTagsByCourseIdResponse
	6,  // 9: course_recommender.CourseTagService.GetCoursesByTagId:output_type -> course_recommender.GetCoursesByTagIdResponse
	8,  // 10: course_recommender.CourseTagService.DeleteCourseTag:output_type -> course_recommender.DeleteCourseTagResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_course_tag_proto_init() }
func file_course_tag_proto_init() {
	if File_course_tag_proto != nil {
		return
	}
	file_course_proto_init()
	file_tag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_tag_proto_rawDesc), len(file_course_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_tag_proto_goTypes,
		DependencyIndexes: file_course_tag_proto_depIdxs,
		MessageInfos:      file_course_tag_proto_msgTypes,
	}.Build()
	File_course_tag_proto = out.File
	file_course_tag_proto_goTypes = nil
	file_course_tag_proto_depIdxs = nil
}
