// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: course_question.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The main CourseQuestion message, representing a question for a course.
type CourseQuestion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId        int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Question        string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	QuestionOptionA string                 `protobuf:"bytes,4,opt,name=question_option_a,json=questionOptionA,proto3" json:"question_option_a,omitempty"`
	QuestionOptionB string                 `protobuf:"bytes,5,opt,name=question_option_b,json=questionOptionB,proto3" json:"question_option_b,omitempty"`
	QuestionOptionC string                 `protobuf:"bytes,6,opt,name=question_option_c,json=questionOptionC,proto3" json:"question_option_c,omitempty"`
	QuestionOptionD string                 `protobuf:"bytes,7,opt,name=question_option_d,json=questionOptionD,proto3" json:"question_option_d,omitempty"`
	CorrectOption   string                 `protobuf:"bytes,8,opt,name=correct_option,json=correctOption,proto3" json:"correct_option,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CourseQuestion) Reset() {
	*x = CourseQuestion{}
	mi := &file_course_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseQuestion) ProtoMessage() {}

func (x *CourseQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseQuestion.ProtoReflect.Descriptor instead.
func (*CourseQuestion) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{0}
}

func (x *CourseQuestion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseQuestion) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CourseQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CourseQuestion) GetQuestionOptionA() string {
	if x != nil {
		return x.QuestionOptionA
	}
	return ""
}

func (x *CourseQuestion) GetQuestionOptionB() string {
	if x != nil {
		return x.QuestionOptionB
	}
	return ""
}

func (x *CourseQuestion) GetQuestionOptionC() string {
	if x != nil {
		return x.QuestionOptionC
	}
	return ""
}

func (x *CourseQuestion) GetQuestionOptionD() string {
	if x != nil {
		return x.QuestionOptionD
	}
	return ""
}

func (x *CourseQuestion) GetCorrectOption() string {
	if x != nil {
		return x.CorrectOption
	}
	return ""
}

// Request to create a new course question.
type CreateCourseQuestionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseId        int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Question        string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	QuestionOptionA string                 `protobuf:"bytes,3,opt,name=question_option_a,json=questionOptionA,proto3" json:"question_option_a,omitempty"`
	QuestionOptionB string                 `protobuf:"bytes,4,opt,name=question_option_b,json=questionOptionB,proto3" json:"question_option_b,omitempty"`
	QuestionOptionC string                 `protobuf:"bytes,5,opt,name=question_option_c,json=questionOptionC,proto3" json:"question_option_c,omitempty"`
	QuestionOptionD string                 `protobuf:"bytes,6,opt,name=question_option_d,json=questionOptionD,proto3" json:"question_option_d,omitempty"`
	CorrectOption   string                 `protobuf:"bytes,7,opt,name=correct_option,json=correctOption,proto3" json:"correct_option,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCourseQuestionRequest) Reset() {
	*x = CreateCourseQuestionRequest{}
	mi := &file_course_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseQuestionRequest) ProtoMessage() {}

func (x *CreateCourseQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseQuestionRequest) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseQuestionRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CreateCourseQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CreateCourseQuestionRequest) GetQuestionOptionA() string {
	if x != nil {
		return x.QuestionOptionA
	}
	return ""
}

func (x *CreateCourseQuestionRequest) GetQuestionOptionB() string {
	if x != nil {
		return x.QuestionOptionB
	}
	return ""
}

func (x *CreateCourseQuestionRequest) GetQuestionOptionC() string {
	if x != nil {
		return x.QuestionOptionC
	}
	return ""
}

func (x *CreateCourseQuestionRequest) GetQuestionOptionD() string {
	if x != nil {
		return x.QuestionOptionD
	}
	return ""
}

func (x *CreateCourseQuestionRequest) GetCorrectOption() string {
	if x != nil {
		return x.CorrectOption
	}
	return ""
}

// Response containing the newly created course question.
type CreateCourseQuestionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CourseQuestion *CourseQuestion        `protobuf:"bytes,1,opt,name=course_question,json=courseQuestion,proto3" json:"course_question,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCourseQuestionResponse) Reset() {
	*x = CreateCourseQuestionResponse{}
	mi := &file_course_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseQuestionResponse) ProtoMessage() {}

func (x *CreateCourseQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseQuestionResponse) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseQuestionResponse) GetCourseQuestion() *CourseQuestion {
	if x != nil {
		return x.CourseQuestion
	}
	return nil
}

// Request to get a course question by its ID.
type GetCourseQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseQuestionRequest) Reset() {
	*x = GetCourseQuestionRequest{}
	mi := &file_course_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseQuestionRequest) ProtoMessage() {}

func (x *GetCourseQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetCourseQuestionRequest) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response containing the requested course question.
type GetCourseQuestionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CourseQuestion *CourseQuestion        `protobuf:"bytes,1,opt,name=course_question,json=courseQuestion,proto3" json:"course_question,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCourseQuestionResponse) Reset() {
	*x = GetCourseQuestionResponse{}
	mi := &file_course_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseQuestionResponse) ProtoMessage() {}

func (x *GetCourseQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetCourseQuestionResponse) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseQuestionResponse) GetCourseQuestion() *CourseQuestion {
	if x != nil {
		return x.CourseQuestion
	}
	return nil
}

// Request to update an existing course question.
type UpdateCourseQuestionRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Question        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	QuestionOptionA *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=question_option_a,json=questionOptionA,proto3" json:"question_option_a,omitempty"`
	QuestionOptionB *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=question_option_b,json=questionOptionB,proto3" json:"question_option_b,omitempty"`
	QuestionOptionC *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=question_option_c,json=questionOptionC,proto3" json:"question_option_c,omitempty"`
	QuestionOptionD *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=question_option_d,json=questionOptionD,proto3" json:"question_option_d,omitempty"`
	CorrectOption   *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=correct_option,json=correctOption,proto3" json:"correct_option,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCourseQuestionRequest) Reset() {
	*x = UpdateCourseQuestionRequest{}
	mi := &file_course_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseQuestionRequest) ProtoMessage() {}

func (x *UpdateCourseQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseQuestionRequest) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCourseQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCourseQuestionRequest) GetQuestion() *wrapperspb.StringValue {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *UpdateCourseQuestionRequest) GetQuestionOptionA() *wrapperspb.StringValue {
	if x != nil {
		return x.QuestionOptionA
	}
	return nil
}

func (x *UpdateCourseQuestionRequest) GetQuestionOptionB() *wrapperspb.StringValue {
	if x != nil {
		return x.QuestionOptionB
	}
	return nil
}

func (x *UpdateCourseQuestionRequest) GetQuestionOptionC() *wrapperspb.StringValue {
	if x != nil {
		return x.QuestionOptionC
	}
	return nil
}

func (x *UpdateCourseQuestionRequest) GetQuestionOptionD() *wrapperspb.StringValue {
	if x != nil {
		return x.QuestionOptionD
	}
	return nil
}

func (x *UpdateCourseQuestionRequest) GetCorrectOption() *wrapperspb.StringValue {
	if x != nil {
		return x.CorrectOption
	}
	return nil
}

// Response containing the updated course question.
type UpdateCourseQuestionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CourseQuestion *CourseQuestion        `protobuf:"bytes,1,opt,name=course_question,json=courseQuestion,proto3" json:"course_question,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCourseQuestionResponse) Reset() {
	*x = UpdateCourseQuestionResponse{}
	mi := &file_course_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseQuestionResponse) ProtoMessage() {}

func (x *UpdateCourseQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseQuestionResponse) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCourseQuestionResponse) GetCourseQuestion() *CourseQuestion {
	if x != nil {
		return x.CourseQuestion
	}
	return nil
}

// Request to list all course questions.
type ListCourseQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCourseQuestionsRequest) Reset() {
	*x = ListCourseQuestionsRequest{}
	mi := &file_course_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseQuestionsRequest) ProtoMessage() {}

func (x *ListCourseQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListCourseQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{7}
}

// Response containing a list of all course questions.
type ListCourseQuestionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseQuestions []*CourseQuestion      `protobuf:"bytes,1,rep,name=course_questions,json=courseQuestions,proto3" json:"course_questions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCourseQuestionsResponse) Reset() {
	*x = ListCourseQuestionsResponse{}
	mi := &file_course_question_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCourseQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCourseQuestionsResponse) ProtoMessage() {}

func (x *ListCourseQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCourseQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListCourseQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{8}
}

func (x *ListCourseQuestionsResponse) GetCourseQuestions() []*CourseQuestion {
	if x != nil {
		return x.CourseQuestions
	}
	return nil
}

// Request to delete a course question by its ID.
type DeleteCourseQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseQuestionRequest) Reset() {
	*x = DeleteCourseQuestionRequest{}
	mi := &file_course_question_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseQuestionRequest) ProtoMessage() {}

func (x *DeleteCourseQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseQuestionRequest) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCourseQuestionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response indicating whether the deletion was successful.
type DeleteCourseQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseQuestionResponse) Reset() {
	*x = DeleteCourseQuestionResponse{}
	mi := &file_course_question_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseQuestionResponse) ProtoMessage() {}

func (x *DeleteCourseQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseQuestionResponse) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCourseQuestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request to get all questions for a specific course.
type GetCourseQuestionsByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseQuestionsByCourseIdRequest) Reset() {
	*x = GetCourseQuestionsByCourseIdRequest{}
	mi := &file_course_question_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseQuestionsByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseQuestionsByCourseIdRequest) ProtoMessage() {}

func (x *GetCourseQuestionsByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseQuestionsByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*GetCourseQuestionsByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{11}
}

func (x *GetCourseQuestionsByCourseIdRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response containing a list of questions for a specific course.
type GetCourseQuestionsByCourseIdResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseQuestions []*CourseQuestion      `protobuf:"bytes,1,rep,name=course_questions,json=courseQuestions,proto3" json:"course_questions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCourseQuestionsByCourseIdResponse) Reset() {
	*x = GetCourseQuestionsByCourseIdResponse{}
	mi := &file_course_question_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseQuestionsByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseQuestionsByCourseIdResponse) ProtoMessage() {}

func (x *GetCourseQuestionsByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_question_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseQuestionsByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*GetCourseQuestionsByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_course_question_proto_rawDescGZIP(), []int{12}
}

func (x *GetCourseQuestionsByCourseIdResponse) GetCourseQuestions() []*CourseQuestion {
	if x != nil {
		return x.CourseQuestions
	}
	return nil
}

var File_course_question_proto protoreflect.FileDescriptor

const file_course_question_proto_rawDesc = "" +
	"\n" +
	"\x15course_question.proto\x12\x12course_recommender\x1a\x1egoogle/protobuf/wrappers.proto\"\xb0\x02\n" +
	"\x0eCourseQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12*\n" +
	"\x11question_option_a\x18\x04 \x01(\tR\x0fquestionOptionA\x12*\n" +
	"\x11question_option_b\x18\x05 \x01(\tR\x0fquestionOptionB\x12*\n" +
	"\x11question_option_c\x18\x06 \x01(\tR\x0fquestionOptionC\x12*\n" +
	"\x11question_option_d\x18\a \x01(\tR\x0fquestionOptionD\x12%\n" +
	"\x0ecorrect_option\x18\b \x01(\tR\rcorrectOption\"\xad\x02\n" +
	"\x1bCreateCourseQuestionRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12*\n" +
	"\x11question_option_a\x18\x03 \x01(\tR\x0fquestionOptionA\x12*\n" +
	"\x11question_option_b\x18\x04 \x01(\tR\x0fquestionOptionB\x12*\n" +
	"\x11question_option_c\x18\x05 \x01(\tR\x0fquestionOptionC\x12*\n" +
	"\x11question_option_d\x18\x06 \x01(\tR\x0fquestionOptionD\x12%\n" +
	"\x0ecorrect_option\x18\a \x01(\tR\rcorrectOption\"k\n" +
	"\x1cCreateCourseQuestionResponse\x12K\n" +
	"\x0fcourse_question\x18\x01 \x01(\v2\".course_recommender.CourseQuestionR\x0ecourseQuestion\"*\n" +
	"\x18GetCourseQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x19GetCourseQuestionResponse\x12K\n" +
	"\x0fcourse_question\x18\x01 \x01(\v2\".course_recommender.CourseQuestionR\x0ecourseQuestion\"\xd4\x03\n" +
	"\x1bUpdateCourseQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x128\n" +
	"\bquestion\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\bquestion\x12H\n" +
	"\x11question_option_a\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x0fquestionOptionA\x12H\n" +
	"\x11question_option_b\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x0fquestionOptionB\x12H\n" +
	"\x11question_option_c\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x0fquestionOptionC\x12H\n" +
	"\x11question_option_d\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x0fquestionOptionD\x12C\n" +
	"\x0ecorrect_option\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\rcorrectOption\"k\n" +
	"\x1cUpdateCourseQuestionResponse\x12K\n" +
	"\x0fcourse_question\x18\x01 \x01(\v2\".course_recommender.CourseQuestionR\x0ecourseQuestion\"\x1c\n" +
	"\x1aListCourseQuestionsRequest\"l\n" +
	"\x1bListCourseQuestionsResponse\x12M\n" +
	"\x10course_questions\x18\x01 \x03(\v2\".course_recommender.CourseQuestionR\x0fcourseQuestions\"-\n" +
	"\x1bDeleteCourseQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x1cDeleteCourseQuestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"#GetCourseQuestionsByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"u\n" +
	"$GetCourseQuestionsByCourseIdResponse\x12M\n" +
	"\x10course_questions\x18\x01 \x03(\v2\".course_recommender.CourseQuestionR\x0fcourseQuestions2\x86\x06\n" +
	"\x15CourseQuestionService\x12y\n" +
	"\x14CreateCourseQuestion\x12/.course_recommender.CreateCourseQuestionRequest\x1a0.course_recommender.CreateCourseQuestionResponse\x12p\n" +
	"\x11GetCourseQuestion\x12,.course_recommender.GetCourseQuestionRequest\x1a-.course_recommender.GetCourseQuestionResponse\x12y\n" +
	"\x14UpdateCourseQuestion\x12/.course_recommender.UpdateCourseQuestionRequest\x1a0.course_recommender.UpdateCourseQuestionResponse\x12v\n" +
	"\x13ListCourseQuestions\x12..course_recommender.ListCourseQuestionsRequest\x1a/.course_recommender.ListCourseQuestionsResponse\x12y\n" +
	"\x14DeleteCourseQuestion\x12/.course_recommender.DeleteCourseQuestionRequest\x1a0.course_recommender.DeleteCourseQuestionResponse\x12\x91\x01\n" +
	"\x1cGetCourseQuestionsByCourseId\x127.course_recommender.GetCourseQuestionsByCourseIdRequest\x1a8.course_recommender.GetCourseQuestionsByCourseIdResponseB\aZ\x05./apib\x06proto3"

var (
	file_course_question_proto_rawDescOnce sync.Once
	file_course_question_proto_rawDescData []byte
)

func file_course_question_proto_rawDescGZIP() []byte {
	file_course_question_proto_rawDescOnce.Do(func() {
		file_course_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_question_proto_rawDesc), len(file_course_question_proto_rawDesc)))
	})
	return file_course_question_proto_rawDescData
}

var file_course_question_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_course_question_proto_goTypes = []any{
	(*CourseQuestion)(nil),                       // 0: course_recommender.CourseQuestion
	(*CreateCourseQuestionRequest)(nil),          // 1: course_recommender.CreateCourseQuestionRequest
	(*CreateCourseQuestionResponse)(nil),         // 2: course_recommender.CreateCourseQuestionResponse
	(*GetCourseQuestionRequest)(nil),             // 3: course_recommender.GetCourseQuestionRequest
	(*GetCourseQuestionResponse)(nil),            // 4: course_recommender.GetCourseQuestionResponse
	(*UpdateCourseQuestionRequest)(nil),          // 5: course_recommender.UpdateCourseQuestionRequest
	(*UpdateCourseQuestionResponse)(nil),         // 6: course_recommender.UpdateCourseQuestionResponse
	(*ListCourseQuestionsRequest)(nil),           // 7: course_recommender.ListCourseQuestionsRequest
	(*ListCourseQuestionsResponse)(nil),          // 8: course_recommender.ListCourseQuestionsResponse
	(*DeleteCourseQuestionRequest)(nil),          // 9: course_recommender.DeleteCourseQuestionRequest
	(*DeleteCourseQuestionResponse)(nil),         // 10: course_recommender.DeleteCourseQuestionResponse
	(*GetCourseQuestionsByCourseIdRequest)(nil),  // 11: course_recommender.GetCourseQuestionsByCourseIdRequest
	(*GetCourseQuestionsByCourseIdResponse)(nil), // 12: course_recommender.GetCourseQuestionsByCourseIdResponse
	(*wrapperspb.StringValue)(nil),               // 13: google.protobuf.StringValue
}
var file_course_question_proto_depIdxs = []int32{
	0,  // 0: course_recommender.CreateCourseQuestionResponse.course_question:type_name -> course_recommender.CourseQuestion
	0,  // 1: course_recommender.GetCourseQuestionResponse.course_question:type_name -> course_recommender.CourseQuestion
	13, // 2: course_recommender.UpdateCourseQuestionRequest.question:type_name -> google.protobuf.StringValue
	13, // 3: course_recommender.UpdateCourseQuestionRequest.question_option_a:type_name -> google.protobuf.StringValue
	13, // 4: course_recommender.UpdateCourseQuestionRequest.question_option_b:type_name -> google.protobuf.StringValue
	13, // 5: course_recommender.UpdateCourseQuestionRequest.question_option_c:type_name -> google.protobuf.StringValue
	13, // 6: course_recommender.UpdateCourseQuestionRequest.question_option_d:type_name -> google.protobuf.StringValue
	13, // 7: course_recommender.UpdateCourseQuestionRequest.correct_option:type_name -> google.protobuf.StringValue
	0,  // 8: course_recommender.UpdateCourseQuestionResponse.course_question:type_name -> course_recommender.CourseQuestion
	0,  // 9: course_recommender.ListCourseQuestionsResponse.course_questions:type_name -> course_recommender.CourseQuestion
	0,  // 10: course_recommender.GetCourseQuestionsByCourseIdResponse.course_questions:type_name -> course_recommender.CourseQuestion
	1,  // 11: course_recommender.CourseQuestionService.CreateCourseQuestion:input_type -> course_recommender.CreateCourseQuestionRequest
	3,  // 12: course_recommender.CourseQuestionService.GetCourseQuestion:input_type -> course_recommender.GetCourseQuestionRequest
	5,  // 13: course_recommender.CourseQuestionService.UpdateCourseQuestion:input_type -> course_recommender.UpdateCourseQuestionRequest
	7,  // 14: course_recommender.CourseQuestionService.ListCourseQuestions:input_type -> course_recommender.ListCourseQuestionsRequest
	9,  // 15: course_recommender.CourseQuestionService.DeleteCourseQuestion:input_type -> course_recommender.DeleteCourseQuestionRequest
	11, // 16: course_recommender.CourseQuestionService.GetCourseQuestionsByCourseId:input_type -> course_recommender.GetCourseQuestionsByCourseIdRequest
	2,  // 17: course_recommender.CourseQuestionService.CreateCourseQuestion:output_type -> course_recommender.CreateCourseQuestionResponse
	4,  // 18: course_recommender.CourseQuestionService.GetCourseQuestion:output_type -> course_recommender.GetCourseQuestionResponse
	6,  // 19: course_recommender.CourseQuestionService.UpdateCourseQuestion:output_type -> course_recommender.UpdateCourseQuestionResponse
	8,  // 20: course_recommender.CourseQuestionService.ListCourseQuestions:output_type -> course_recommender.ListCourseQuestionsResponse
	10, // 21: course_recommender.CourseQuestionService.DeleteCourseQuestion:output_type -> course_recommender.DeleteCourseQuestionResponse
	12, // 22: course_recommender.CourseQuestionService.GetCourseQuestionsByCourseId:output_type -> course_recommender.GetCourseQuestionsByCourseIdResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_course_question_proto_init() }
func file_course_question_proto_init() {
	if File_course_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_question_proto_rawDesc), len(file_course_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_question_proto_goTypes,
		DependencyIndexes: file_course_question_proto_depIdxs,
		MessageInfos:      file_course_question_proto_msgTypes,
	}.Build()
	File_course_question_proto = out.File
	file_course_question_proto_goTypes = nil
	file_course_question_proto_depIdxs = nil
}
