// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: degree_type.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The main DegreeType message, representing a degree type in the database.
type DegreeType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DegreeName    string                 `protobuf:"bytes,2,opt,name=degree_name,json=degreeName,proto3" json:"degree_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DegreeType) Reset() {
	*x = DegreeType{}
	mi := &file_degree_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DegreeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DegreeType) ProtoMessage() {}

func (x *DegreeType) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DegreeType.ProtoReflect.Descriptor instead.
func (*DegreeType) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{0}
}

func (x *DegreeType) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DegreeType) GetDegreeName() string {
	if x != nil {
		return x.DegreeName
	}
	return ""
}

// Request to create a new degree type.
type CreateDegreeTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeName    string                 `protobuf:"bytes,1,opt,name=degree_name,json=degreeName,proto3" json:"degree_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDegreeTypeRequest) Reset() {
	*x = CreateDegreeTypeRequest{}
	mi := &file_degree_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDegreeTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDegreeTypeRequest) ProtoMessage() {}

func (x *CreateDegreeTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDegreeTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateDegreeTypeRequest) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDegreeTypeRequest) GetDegreeName() string {
	if x != nil {
		return x.DegreeName
	}
	return ""
}

// Response containing the newly created degree type.
type CreateDegreeTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeType    *DegreeType            `protobuf:"bytes,1,opt,name=degree_type,json=degreeType,proto3" json:"degree_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDegreeTypeResponse) Reset() {
	*x = CreateDegreeTypeResponse{}
	mi := &file_degree_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDegreeTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDegreeTypeResponse) ProtoMessage() {}

func (x *CreateDegreeTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDegreeTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateDegreeTypeResponse) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDegreeTypeResponse) GetDegreeType() *DegreeType {
	if x != nil {
		return x.DegreeType
	}
	return nil
}

// Request to get a degree type by its ID.
type GetDegreeTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDegreeTypeRequest) Reset() {
	*x = GetDegreeTypeRequest{}
	mi := &file_degree_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDegreeTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreeTypeRequest) ProtoMessage() {}

func (x *GetDegreeTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreeTypeRequest.ProtoReflect.Descriptor instead.
func (*GetDegreeTypeRequest) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{3}
}

func (x *GetDegreeTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response containing the requested degree type.
type GetDegreeTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeType    *DegreeType            `protobuf:"bytes,1,opt,name=degree_type,json=degreeType,proto3" json:"degree_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDegreeTypeResponse) Reset() {
	*x = GetDegreeTypeResponse{}
	mi := &file_degree_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDegreeTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreeTypeResponse) ProtoMessage() {}

func (x *GetDegreeTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreeTypeResponse.ProtoReflect.Descriptor instead.
func (*GetDegreeTypeResponse) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{4}
}

func (x *GetDegreeTypeResponse) GetDegreeType() *DegreeType {
	if x != nil {
		return x.DegreeType
	}
	return nil
}

// Request to get degree types by name.
type GetDegreeTypeByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeName    string                 `protobuf:"bytes,1,opt,name=degree_name,json=degreeName,proto3" json:"degree_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDegreeTypeByNameRequest) Reset() {
	*x = GetDegreeTypeByNameRequest{}
	mi := &file_degree_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDegreeTypeByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreeTypeByNameRequest) ProtoMessage() {}

func (x *GetDegreeTypeByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreeTypeByNameRequest.ProtoReflect.Descriptor instead.
func (*GetDegreeTypeByNameRequest) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{5}
}

func (x *GetDegreeTypeByNameRequest) GetDegreeName() string {
	if x != nil {
		return x.DegreeName
	}
	return ""
}

// Response containing a list of degree types that match the name.
type GetDegreeTypeByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeTypes   []*DegreeType          `protobuf:"bytes,1,rep,name=degree_types,json=degreeTypes,proto3" json:"degree_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDegreeTypeByNameResponse) Reset() {
	*x = GetDegreeTypeByNameResponse{}
	mi := &file_degree_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDegreeTypeByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreeTypeByNameResponse) ProtoMessage() {}

func (x *GetDegreeTypeByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreeTypeByNameResponse.ProtoReflect.Descriptor instead.
func (*GetDegreeTypeByNameResponse) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{6}
}

func (x *GetDegreeTypeByNameResponse) GetDegreeTypes() []*DegreeType {
	if x != nil {
		return x.DegreeTypes
	}
	return nil
}

// Request to update an existing degree type.
type UpdateDegreeTypeRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DegreeName    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=degree_name,json=degreeName,proto3" json:"degree_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDegreeTypeRequest) Reset() {
	*x = UpdateDegreeTypeRequest{}
	mi := &file_degree_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDegreeTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDegreeTypeRequest) ProtoMessage() {}

func (x *UpdateDegreeTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDegreeTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateDegreeTypeRequest) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDegreeTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDegreeTypeRequest) GetDegreeName() *wrapperspb.StringValue {
	if x != nil {
		return x.DegreeName
	}
	return nil
}

// Response containing the updated degree type.
type UpdateDegreeTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeType    *DegreeType            `protobuf:"bytes,1,opt,name=degree_type,json=degreeType,proto3" json:"degree_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDegreeTypeResponse) Reset() {
	*x = UpdateDegreeTypeResponse{}
	mi := &file_degree_type_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDegreeTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDegreeTypeResponse) ProtoMessage() {}

func (x *UpdateDegreeTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDegreeTypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateDegreeTypeResponse) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDegreeTypeResponse) GetDegreeType() *DegreeType {
	if x != nil {
		return x.DegreeType
	}
	return nil
}

// Request to list all degree types.
type ListDegreeTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDegreeTypesRequest) Reset() {
	*x = ListDegreeTypesRequest{}
	mi := &file_degree_type_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDegreeTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDegreeTypesRequest) ProtoMessage() {}

func (x *ListDegreeTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDegreeTypesRequest.ProtoReflect.Descriptor instead.
func (*ListDegreeTypesRequest) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{9}
}

// Response containing a list of all degree types.
type ListDegreeTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeTypes   []*DegreeType          `protobuf:"bytes,1,rep,name=degree_types,json=degreeTypes,proto3" json:"degree_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDegreeTypesResponse) Reset() {
	*x = ListDegreeTypesResponse{}
	mi := &file_degree_type_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDegreeTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDegreeTypesResponse) ProtoMessage() {}

func (x *ListDegreeTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDegreeTypesResponse.ProtoReflect.Descriptor instead.
func (*ListDegreeTypesResponse) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{10}
}

func (x *ListDegreeTypesResponse) GetDegreeTypes() []*DegreeType {
	if x != nil {
		return x.DegreeTypes
	}
	return nil
}

// Request to delete a degree type by its ID.
type DeleteDegreeTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDegreeTypeRequest) Reset() {
	*x = DeleteDegreeTypeRequest{}
	mi := &file_degree_type_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDegreeTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDegreeTypeRequest) ProtoMessage() {}

func (x *DeleteDegreeTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDegreeTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteDegreeTypeRequest) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDegreeTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response indicating whether the deletion was successful.
type DeleteDegreeTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDegreeTypeResponse) Reset() {
	*x = DeleteDegreeTypeResponse{}
	mi := &file_degree_type_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDegreeTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDegreeTypeResponse) ProtoMessage() {}

func (x *DeleteDegreeTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_type_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDegreeTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteDegreeTypeResponse) Descriptor() ([]byte, []int) {
	return file_degree_type_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDegreeTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_degree_type_proto protoreflect.FileDescriptor

const file_degree_type_proto_rawDesc = "" +
	"\n" +
	"\x11degree_type.proto\x12\x12course_recommender\x1a\x1egoogle/protobuf/wrappers.proto\"=\n" +
	"\n" +
	"DegreeType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vdegree_name\x18\x02 \x01(\tR\n" +
	"degreeName\":\n" +
	"\x17CreateDegreeTypeRequest\x12\x1f\n" +
	"\vdegree_name\x18\x01 \x01(\tR\n" +
	"degreeName\"[\n" +
	"\x18CreateDegreeTypeResponse\x12?\n" +
	"\vdegree_type\x18\x01 \x01(\v2\x1e.course_recommender.DegreeTypeR\n" +
	"degreeType\"&\n" +
	"\x14GetDegreeTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"X\n" +
	"\x15GetDegreeTypeResponse\x12?\n" +
	"\vdegree_type\x18\x01 \x01(\v2\x1e.course_recommender.DegreeTypeR\n" +
	"degreeType\"=\n" +
	"\x1aGetDegreeTypeByNameRequest\x12\x1f\n" +
	"\vdegree_name\x18\x01 \x01(\tR\n" +
	"degreeName\"`\n" +
	"\x1bGetDegreeTypeByNameResponse\x12A\n" +
	"\fdegree_types\x18\x01 \x03(\v2\x1e.course_recommender.DegreeTypeR\vdegreeTypes\"h\n" +
	"\x17UpdateDegreeTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12=\n" +
	"\vdegree_name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"degreeName\"[\n" +
	"\x18UpdateDegreeTypeResponse\x12?\n" +
	"\vdegree_type\x18\x01 \x01(\v2\x1e.course_recommender.DegreeTypeR\n" +
	"degreeType\"\x18\n" +
	"\x16ListDegreeTypesRequest\"\\\n" +
	"\x17ListDegreeTypesResponse\x12A\n" +
	"\fdegree_types\x18\x01 \x03(\v2\x1e.course_recommender.DegreeTypeR\vdegreeTypes\")\n" +
	"\x17DeleteDegreeTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x18DeleteDegreeTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xaa\x05\n" +
	"\x11DegreeTypeService\x12m\n" +
	"\x10CreateDegreeType\x12+.course_recommender.CreateDegreeTypeRequest\x1a,.course_recommender.CreateDegreeTypeResponse\x12d\n" +
	"\rGetDegreeType\x12(.course_recommender.GetDegreeTypeRequest\x1a).course_recommender.GetDegreeTypeResponse\x12v\n" +
	"\x13GetDegreeTypeByName\x12..course_recommender.GetDegreeTypeByNameRequest\x1a/.course_recommender.GetDegreeTypeByNameResponse\x12m\n" +
	"\x10UpdateDegreeType\x12+.course_recommender.UpdateDegreeTypeRequest\x1a,.course_recommender.UpdateDegreeTypeResponse\x12j\n" +
	"\x0fListDegreeTypes\x12*.course_recommender.ListDegreeTypesRequest\x1a+.course_recommender.ListDegreeTypesResponse\x12m\n" +
	"\x10DeleteDegreeType\x12+.course_recommender.DeleteDegreeTypeRequest\x1a,.course_recommender.DeleteDegreeTypeResponseB\aZ\x05./apib\x06proto3"

var (
	file_degree_type_proto_rawDescOnce sync.Once
	file_degree_type_proto_rawDescData []byte
)

func file_degree_type_proto_rawDescGZIP() []byte {
	file_degree_type_proto_rawDescOnce.Do(func() {
		file_degree_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_degree_type_proto_rawDesc), len(file_degree_type_proto_rawDesc)))
	})
	return file_degree_type_proto_rawDescData
}

var file_degree_type_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_degree_type_proto_goTypes = []any{
	(*DegreeType)(nil),                  // 0: course_recommender.DegreeType
	(*CreateDegreeTypeRequest)(nil),     // 1: course_recommender.CreateDegreeTypeRequest
	(*CreateDegreeTypeResponse)(nil),    // 2: course_recommender.CreateDegreeTypeResponse
	(*GetDegreeTypeRequest)(nil),        // 3: course_recommender.GetDegreeTypeRequest
	(*GetDegreeTypeResponse)(nil),       // 4: course_recommender.GetDegreeTypeResponse
	(*GetDegreeTypeByNameRequest)(nil),  // 5: course_recommender.GetDegreeTypeByNameRequest
	(*GetDegreeTypeByNameResponse)(nil), // 6: course_recommender.GetDegreeTypeByNameResponse
	(*UpdateDegreeTypeRequest)(nil),     // 7: course_recommender.UpdateDegreeTypeRequest
	(*UpdateDegreeTypeResponse)(nil),    // 8: course_recommender.UpdateDegreeTypeResponse
	(*ListDegreeTypesRequest)(nil),      // 9: course_recommender.ListDegreeTypesRequest
	(*ListDegreeTypesResponse)(nil),     // 10: course_recommender.ListDegreeTypesResponse
	(*DeleteDegreeTypeRequest)(nil),     // 11: course_recommender.DeleteDegreeTypeRequest
	(*DeleteDegreeTypeResponse)(nil),    // 12: course_recommender.DeleteDegreeTypeResponse
	(*wrapperspb.StringValue)(nil),      // 13: google.protobuf.StringValue
}
var file_degree_type_proto_depIdxs = []int32{
	0,  // 0: course_recommender.CreateDegreeTypeResponse.degree_type:type_name -> course_recommender.DegreeType
	0,  // 1: course_recommender.GetDegreeTypeResponse.degree_type:type_name -> course_recommender.DegreeType
	0,  // 2: course_recommender.GetDegreeTypeByNameResponse.degree_types:type_name -> course_recommender.DegreeType
	13, // 3: course_recommender.UpdateDegreeTypeRequest.degree_name:type_name -> google.protobuf.StringValue
	0,  // 4: course_recommender.UpdateDegreeTypeResponse.degree_type:type_name -> course_recommender.DegreeType
	0,  // 5: course_recommender.ListDegreeTypesResponse.degree_types:type_name -> course_recommender.DegreeType
	1,  // 6: course_recommender.DegreeTypeService.CreateDegreeType:input_type -> course_recommender.CreateDegreeTypeRequest
	3,  // 7: course_recommender.DegreeTypeService.GetDegreeType:input_type -> course_recommender.GetDegreeTypeRequest
	5,  // 8: course_recommender.DegreeTypeService.GetDegreeTypeByName:input_type -> course_recommender.GetDegreeTypeByNameRequest
	7,  // 9: course_recommender.DegreeTypeService.UpdateDegreeType:input_type -> course_recommender.UpdateDegreeTypeRequest
	9,  // 10: course_recommender.DegreeTypeService.ListDegreeTypes:input_type -> course_recommender.ListDegreeTypesRequest
	11, // 11: course_recommender.DegreeTypeService.DeleteDegreeType:input_type -> course_recommender.DeleteDegreeTypeRequest
	2,  // 12: course_recommender.DegreeTypeService.CreateDegreeType:output_type -> course_recommender.CreateDegreeTypeResponse
	4,  // 13: course_recommender.DegreeTypeService.GetDegreeType:output_type -> course_recommender.GetDegreeTypeResponse
	6,  // 14: course_recommender.DegreeTypeService.GetDegreeTypeByName:output_type -> course_recommender.GetDegreeTypeByNameResponse
	8,  // 15: course_recommender.DegreeTypeService.UpdateDegreeType:output_type -> course_recommender.UpdateDegreeTypeResponse
	10, // 16: course_recommender.DegreeTypeService.ListDegreeTypes:output_type -> course_recommender.ListDegreeTypesResponse
	12, // 17: course_recommender.DegreeTypeService.DeleteDegreeType:output_type -> course_recommender.DeleteDegreeTypeResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_degree_type_proto_init() }
func file_degree_type_proto_init() {
	if File_degree_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_degree_type_proto_rawDesc), len(file_degree_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_degree_type_proto_goTypes,
		DependencyIndexes: file_degree_type_proto_depIdxs,
		MessageInfos:      file_degree_type_proto_msgTypes,
	}.Build()
	File_degree_type_proto = out.File
	file_degree_type_proto_goTypes = nil
	file_degree_type_proto_depIdxs = nil
}
