// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: degree_course.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The DegreeCourse message, representing the many-to-many relationship
// between degree types and courses.
type DegreeCourse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeTypeId  int64                  `protobuf:"varint,1,opt,name=degree_type_id,json=degreeTypeId,proto3" json:"degree_type_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DegreeCourse) Reset() {
	*x = DegreeCourse{}
	mi := &file_degree_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DegreeCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DegreeCourse) ProtoMessage() {}

func (x *DegreeCourse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DegreeCourse.ProtoReflect.Descriptor instead.
func (*DegreeCourse) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{0}
}

func (x *DegreeCourse) GetDegreeTypeId() int64 {
	if x != nil {
		return x.DegreeTypeId
	}
	return 0
}

func (x *DegreeCourse) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Request to create a new degree-course association.
type CreateDegreeCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeTypeId  int64                  `protobuf:"varint,1,opt,name=degree_type_id,json=degreeTypeId,proto3" json:"degree_type_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDegreeCourseRequest) Reset() {
	*x = CreateDegreeCourseRequest{}
	mi := &file_degree_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDegreeCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDegreeCourseRequest) ProtoMessage() {}

func (x *CreateDegreeCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDegreeCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateDegreeCourseRequest) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDegreeCourseRequest) GetDegreeTypeId() int64 {
	if x != nil {
		return x.DegreeTypeId
	}
	return 0
}

func (x *CreateDegreeCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response containing the newly created degree-course association.
type CreateDegreeCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeCourse  *DegreeCourse          `protobuf:"bytes,1,opt,name=degree_course,json=degreeCourse,proto3" json:"degree_course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDegreeCourseResponse) Reset() {
	*x = CreateDegreeCourseResponse{}
	mi := &file_degree_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDegreeCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDegreeCourseResponse) ProtoMessage() {}

func (x *CreateDegreeCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDegreeCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateDegreeCourseResponse) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDegreeCourseResponse) GetDegreeCourse() *DegreeCourse {
	if x != nil {
		return x.DegreeCourse
	}
	return nil
}

// Request to get all courses for a specific degree type.
type GetCoursesByDegreeIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeTypeId  int64                  `protobuf:"varint,1,opt,name=degree_type_id,json=degreeTypeId,proto3" json:"degree_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesByDegreeIdRequest) Reset() {
	*x = GetCoursesByDegreeIdRequest{}
	mi := &file_degree_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesByDegreeIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesByDegreeIdRequest) ProtoMessage() {}

func (x *GetCoursesByDegreeIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesByDegreeIdRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesByDegreeIdRequest) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{3}
}

func (x *GetCoursesByDegreeIdRequest) GetDegreeTypeId() int64 {
	if x != nil {
		return x.DegreeTypeId
	}
	return 0
}

// Response containing a list of courses for a specific degree type.
type GetCoursesByDegreeIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesByDegreeIdResponse) Reset() {
	*x = GetCoursesByDegreeIdResponse{}
	mi := &file_degree_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesByDegreeIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesByDegreeIdResponse) ProtoMessage() {}

func (x *GetCoursesByDegreeIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesByDegreeIdResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesByDegreeIdResponse) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCoursesByDegreeIdResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

// Request to get all degree types for a specific course.
type GetDegreesByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDegreesByCourseIdRequest) Reset() {
	*x = GetDegreesByCourseIdRequest{}
	mi := &file_degree_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDegreesByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreesByCourseIdRequest) ProtoMessage() {}

func (x *GetDegreesByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreesByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*GetDegreesByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{5}
}

func (x *GetDegreesByCourseIdRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response containing a list of degree types for a specific course.
type GetDegreesByCourseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeTypes   []*DegreeType          `protobuf:"bytes,1,rep,name=degree_types,json=degreeTypes,proto3" json:"degree_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDegreesByCourseIdResponse) Reset() {
	*x = GetDegreesByCourseIdResponse{}
	mi := &file_degree_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDegreesByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDegreesByCourseIdResponse) ProtoMessage() {}

func (x *GetDegreesByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDegreesByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*GetDegreesByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{6}
}

func (x *GetDegreesByCourseIdResponse) GetDegreeTypes() []*DegreeType {
	if x != nil {
		return x.DegreeTypes
	}
	return nil
}

// Request to delete a degree-course association.
type DeleteDegreeCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DegreeTypeId  int64                  `protobuf:"varint,1,opt,name=degree_type_id,json=degreeTypeId,proto3" json:"degree_type_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDegreeCourseRequest) Reset() {
	*x = DeleteDegreeCourseRequest{}
	mi := &file_degree_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDegreeCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDegreeCourseRequest) ProtoMessage() {}

func (x *DeleteDegreeCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDegreeCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteDegreeCourseRequest) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDegreeCourseRequest) GetDegreeTypeId() int64 {
	if x != nil {
		return x.DegreeTypeId
	}
	return 0
}

func (x *DeleteDegreeCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response indicating whether the deletion was successful.
type DeleteDegreeCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDegreeCourseResponse) Reset() {
	*x = DeleteDegreeCourseResponse{}
	mi := &file_degree_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDegreeCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDegreeCourseResponse) ProtoMessage() {}

func (x *DeleteDegreeCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degree_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDegreeCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteDegreeCourseResponse) Descriptor() ([]byte, []int) {
	return file_degree_course_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDegreeCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_degree_course_proto protoreflect.FileDescriptor

const file_degree_course_proto_rawDesc = "" +
	"\n" +
	"\x13degree_course.proto\x12\x12course_recommender\x1a\fcourse.proto\x1a\x11degree_type.proto\"Q\n" +
	"\fDegreeCourse\x12$\n" +
	"\x0edegree_type_id\x18\x01 \x01(\x03R\fdegreeTypeId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"^\n" +
	"\x19CreateDegreeCourseRequest\x12$\n" +
	"\x0edegree_type_id\x18\x01 \x01(\x03R\fdegreeTypeId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"c\n" +
	"\x1aCreateDegreeCourseResponse\x12E\n" +
	"\rdegree_course\x18\x01 \x01(\v2 .course_recommender.DegreeCourseR\fdegreeCourse\"C\n" +
	"\x1bGetCoursesByDegreeIdRequest\x12$\n" +
	"\x0edegree_type_id\x18\x01 \x01(\x03R\fdegreeTypeId\"T\n" +
	"\x1cGetCoursesByDegreeIdResponse\x124\n" +
	"\acourses\x18\x01 \x03(\v2\x1a.course_recommender.CourseR\acourses\":\n" +
	"\x1bGetDegreesByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"a\n" +
	"\x1cGetDegreesByCourseIdResponse\x12A\n" +
	"\fdegree_types\x18\x01 \x03(\v2\x1e.course_recommender.DegreeTypeR\vdegreeTypes\"^\n" +
	"\x19DeleteDegreeCourseRequest\x12$\n" +
	"\x0edegree_type_id\x18\x01 \x01(\x03R\fdegreeTypeId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"6\n" +
	"\x1aDeleteDegreeCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf5\x03\n" +
	"\x13DegreeCourseService\x12s\n" +
	"\x12CreateDegreeCourse\x12-.course_recommender.CreateDegreeCourseRequest\x1a..course_recommender.CreateDegreeCourseResponse\x12y\n" +
	"\x14GetCoursesByDegreeId\x12/.course_recommender.GetCoursesByDegreeIdRequest\x1a0.course_recommender.GetCoursesByDegreeIdResponse\x12y\n" +
	"\x14GetDegreesByCourseId\x12/.course_recommender.GetDegreesByCourseIdRequest\x1a0.course_recommender.GetDegreesByCourseIdResponse\x12s\n" +
	"\x12DeleteDegreeCourse\x12-.course_recommender.DeleteDegreeCourseRequest\x1a..course_recommender.DeleteDegreeCourseResponseB\aZ\x05./apib\x06proto3"

var (
	file_degree_course_proto_rawDescOnce sync.Once
	file_degree_course_proto_rawDescData []byte
)

func file_degree_course_proto_rawDescGZIP() []byte {
	file_degree_course_proto_rawDescOnce.Do(func() {
		file_degree_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_degree_course_proto_rawDesc), len(file_degree_course_proto_rawDesc)))
	})
	return file_degree_course_proto_rawDescData
}

var file_degree_course_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_degree_course_proto_goTypes = []any{
	(*DegreeCourse)(nil),                 // 0: course_recommender.DegreeCourse
	(*CreateDegreeCourseRequest)(nil),    // 1: course_recommender.CreateDegreeCourseRequest
	(*CreateDegreeCourseResponse)(nil),   // 2: course_recommender.CreateDegreeCourseResponse
	(*GetCoursesByDegreeIdRequest)(nil),  // 3: course_recommender.GetCoursesByDegreeIdRequest
	(*GetCoursesByDegreeIdResponse)(nil), // 4: course_recommender.GetCoursesByDegreeIdResponse
	(*GetDegreesByCourseIdRequest)(nil),  // 5: course_recommender.GetDegreesByCourseIdRequest
	(*GetDegreesByCourseIdResponse)(nil), // 6: course_recommender.GetDegreesByCourseIdResponse
	(*DeleteDegreeCourseRequest)(nil),    // 7: course_recommender.DeleteDegreeCourseRequest
	(*DeleteDegreeCourseResponse)(nil),   // 8: course_recommender.DeleteDegreeCourseResponse
	(*Course)(nil),                       // 9: course_recommender.Course
	(*DegreeType)(nil),                   // 10: course_recommender.DegreeType
}
var file_degree_course_proto_depIdxs = []int32{
	0,  // 0: course_recommender.CreateDegreeCourseResponse.degree_course:type_name -> course_recommender.DegreeCourse
	9,  // 1: course_recommender.GetCoursesByDegreeIdResponse.courses:type_name -> course_recommender.Course
	10, // 2: course_recommender.GetDegreesByCourseIdResponse.degree_types:type_name -> course_recommender.DegreeType
	1,  // 3: course_recommender.DegreeCourseService.CreateDegreeCourse:input_type -> course_recommender.CreateDegreeCourseRequest
	3,  // 4: course_recommender.DegreeCourseService.GetCoursesByDegreeId:input_type -> course_recommender.GetCoursesByDegreeIdRequest
	5,  // 5: course_recommender.DegreeCourseService.GetDegreesByCourseId:input_type -> course_recommender.GetDegreesByCourseIdRequest
	7,  // 6: course_recommender.DegreeCourseService.DeleteDegreeCourse:input_type -> course_recommender.DeleteDegreeCourseRequest
	2,  // 7: course_recommender.DegreeCourseService.CreateDegreeCourse:output_type -> course_recommender.CreateDegreeCourseResponse
	4,  // 8: course_recommender.DegreeCourseService.GetCoursesByDegreeId:output_type -> course_recommender.GetCoursesByDegreeIdResponse
	6,  // 9: course_recommender.DegreeCourseService.GetDegreesByCourseId:output_type -> course_recommender.GetDegreesByCourseIdResponse
	8,  // 10: course_recommender.DegreeCourseService.DeleteDegreeCourse:output_type -> course_recommender.DeleteDegreeCourseResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_degree_course_proto_init() }
func file_degree_course_proto_init() {
	if File_degree_course_proto != nil {
		return
	}
	file_course_proto_init()
	file_degree_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_degree_course_proto_rawDesc), len(file_degree_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_degree_course_proto_goTypes,
		DependencyIndexes: file_degree_course_proto_depIdxs,
		MessageInfos:      file_degree_course_proto_msgTypes,
	}.Build()
	File_degree_course_proto = out.File
	file_degree_course_proto_goTypes = nil
	file_degree_course_proto_depIdxs = nil
}
