// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: recommend.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	InterestTags  []int64                `protobuf:"varint,2,rep,packed,name=interest_tags,json=interestTags,proto3" json:"interest_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_recommend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *RecommendRequest) GetInterestTags() []int64 {
	if x != nil {
		return x.InterestTags
	}
	return nil
}

type CoursesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        []*Course              `protobuf:"bytes,1,rep,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoursesList) Reset() {
	*x = CoursesList{}
	mi := &file_recommend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoursesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoursesList) ProtoMessage() {}

func (x *CoursesList) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoursesList.ProtoReflect.Descriptor instead.
func (*CoursesList) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{1}
}

func (x *CoursesList) GetCourse() []*Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type RecommendResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Recommendations map[string]*CoursesList `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_recommend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendResponse) GetRecommendations() map[string]*CoursesList {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_recommend_proto protoreflect.FileDescriptor

const file_recommend_proto_rawDesc = "" +
	"\n" +
	"\x0frecommend.proto\x12\x12course_recommender\x1a\fcourse.proto\"V\n" +
	"\x10RecommendRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03R\tstudentId\x12#\n" +
	"\rinterest_tags\x18\x02 \x03(\x03R\finterestTags\"A\n" +
	"\vCoursesList\x122\n" +
	"\x06course\x18\x01 \x03(\v2\x1a.course_recommender.CourseR\x06course\"\xde\x01\n" +
	"\x11RecommendResponse\x12d\n" +
	"\x0frecommendations\x18\x01 \x03(\v2:.course_recommender.RecommendResponse.RecommendationsEntryR\x0frecommendations\x1ac\n" +
	"\x14RecommendationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.course_recommender.CoursesListR\x05value:\x028\x01B\aZ\x05./apib\x06proto3"

var (
	file_recommend_proto_rawDescOnce sync.Once
	file_recommend_proto_rawDescData []byte
)

func file_recommend_proto_rawDescGZIP() []byte {
	file_recommend_proto_rawDescOnce.Do(func() {
		file_recommend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommend_proto_rawDesc), len(file_recommend_proto_rawDesc)))
	})
	return file_recommend_proto_rawDescData
}

var file_recommend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_recommend_proto_goTypes = []any{
	(*RecommendRequest)(nil),  // 0: course_recommender.RecommendRequest
	(*CoursesList)(nil),       // 1: course_recommender.CoursesList
	(*RecommendResponse)(nil), // 2: course_recommender.RecommendResponse
	nil,                       // 3: course_recommender.RecommendResponse.RecommendationsEntry
	(*Course)(nil),            // 4: course_recommender.Course
}
var file_recommend_proto_depIdxs = []int32{
	4, // 0: course_recommender.CoursesList.course:type_name -> course_recommender.Course
	3, // 1: course_recommender.RecommendResponse.recommendations:type_name -> course_recommender.RecommendResponse.RecommendationsEntry
	1, // 2: course_recommender.RecommendResponse.RecommendationsEntry.value:type_name -> course_recommender.CoursesList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_recommend_proto_init() }
func file_recommend_proto_init() {
	if File_recommend_proto != nil {
		return
	}
	file_course_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommend_proto_rawDesc), len(file_recommend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recommend_proto_goTypes,
		DependencyIndexes: file_recommend_proto_depIdxs,
		MessageInfos:      file_recommend_proto_msgTypes,
	}.Build()
	File_recommend_proto = out.File
	file_recommend_proto_goTypes = nil
	file_recommend_proto_depIdxs = nil
}
