// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: root.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_root_proto protoreflect.FileDescriptor

const file_root_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"root.proto\x12\x12course_recommender\x1a\fcourse.proto\x1a\x15course_question.proto\x1a\x10course_tag.proto\x1a\x13degree_course.proto\x1a\x11degree_type.proto\x1a\rstudent.proto\x1a\x14student_course.proto\x1a\ttag.proto2\xec$\n" +
	"\x18CourseRecommenderService\x12a\n" +
	"\fCreateCourse\x12'.course_recommender.CreateCourseRequest\x1a(.course_recommender.CreateCourseResponse\x12X\n" +
	"\tGetCourse\x12$.course_recommender.GetCourseRequest\x1a%.course_recommender.GetCourseResponse\x12j\n" +
	"\x0fGetCourseByName\x12*.course_recommender.GetCourseByNameRequest\x1a+.course_recommender.GetCourseByNameResponse\x12a\n" +
	"\fUpdateCourse\x12'.course_recommender.UpdateCourseRequest\x1a(.course_recommender.UpdateCourseResponse\x12^\n" +
	"\vListCourses\x12&.course_recommender.ListCoursesRequest\x1a'.course_recommender.ListCoursesResponse\x12a\n" +
	"\fDeleteCourse\x12'.course_recommender.DeleteCourseRequest\x1a(.course_recommender.DeleteCourseResponse\x12y\n" +
	"\x14CreateCourseQuestion\x12/.course_recommender.CreateCourseQuestionRequest\x1a0.course_recommender.CreateCourseQuestionResponse\x12p\n" +
	"\x11GetCourseQuestion\x12,.course_recommender.GetCourseQuestionRequest\x1a-.course_recommender.GetCourseQuestionResponse\x12y\n" +
	"\x14UpdateCourseQuestion\x12/.course_recommender.UpdateCourseQuestionRequest\x1a0.course_recommender.UpdateCourseQuestionResponse\x12v\n" +
	"\x13ListCourseQuestions\x12..course_recommender.ListCourseQuestionsRequest\x1a/.course_recommender.ListCourseQuestionsResponse\x12y\n" +
	"\x14DeleteCourseQuestion\x12/.course_recommender.DeleteCourseQuestionRequest\x1a0.course_recommender.DeleteCourseQuestionResponse\x12\x91\x01\n" +
	"\x1cGetCourseQuestionsByCourseId\x127.course_recommender.GetCourseQuestionsByCourseIdRequest\x1a8.course_recommender.GetCourseQuestionsByCourseIdResponse\x12j\n" +
	"\x0fCreateCourseTag\x12*.course_recommender.CreateCourseTagRequest\x1a+.course_recommender.CreateCourseTagResponse\x12p\n" +
	"\x11GetTagsByCourseId\x12,.course_recommender.GetTagsByCourseIdRequest\x1a-.course_recommender.GetTagsByCourseIdResponse\x12p\n" +
	"\x11GetCoursesByTagId\x12,.course_recommender.GetCoursesByTagIdRequest\x1a-.course_recommender.GetCoursesByTagIdResponse\x12j\n" +
	"\x0fDeleteCourseTag\x12*.course_recommender.DeleteCourseTagRequest\x1a+.course_recommender.DeleteCourseTagResponse\x12s\n" +
	"\x12CreateDegreeCourse\x12-.course_recommender.CreateDegreeCourseRequest\x1a..course_recommender.CreateDegreeCourseResponse\x12y\n" +
	"\x14GetCoursesByDegreeId\x12/.course_recommender.GetCoursesByDegreeIdRequest\x1a0.course_recommender.GetCoursesByDegreeIdResponse\x12y\n" +
	"\x14GetDegreesByCourseId\x12/.course_recommender.GetDegreesByCourseIdRequest\x1a0.course_recommender.GetDegreesByCourseIdResponse\x12s\n" +
	"\x12DeleteDegreeCourse\x12-.course_recommender.DeleteDegreeCourseRequest\x1a..course_recommender.DeleteDegreeCourseResponse\x12m\n" +
	"\x10CreateDegreeType\x12+.course_recommender.CreateDegreeTypeRequest\x1a,.course_recommender.CreateDegreeTypeResponse\x12d\n" +
	"\rGetDegreeType\x12(.course_recommender.GetDegreeTypeRequest\x1a).course_recommender.GetDegreeTypeResponse\x12v\n" +
	"\x13GetDegreeTypeByName\x12..course_recommender.GetDegreeTypeByNameRequest\x1a/.course_recommender.GetDegreeTypeByNameResponse\x12m\n" +
	"\x10UpdateDegreeType\x12+.course_recommender.UpdateDegreeTypeRequest\x1a,.course_recommender.UpdateDegreeTypeResponse\x12j\n" +
	"\x0fListDegreeTypes\x12*.course_recommender.ListDegreeTypesRequest\x1a+.course_recommender.ListDegreeTypesResponse\x12m\n" +
	"\x10DeleteDegreeType\x12+.course_recommender.DeleteDegreeTypeRequest\x1a,.course_recommender.DeleteDegreeTypeResponse\x12d\n" +
	"\rCreateStudent\x12(.course_recommender.CreateStudentRequest\x1a).course_recommender.CreateStudentResponse\x12[\n" +
	"\n" +
	"GetStudent\x12%.course_recommender.GetStudentRequest\x1a&.course_recommender.GetStudentResponse\x12p\n" +
	"\x11GetStudentByEmail\x12,.course_recommender.GetStudentByEmailRequest\x1a-.course_recommender.GetStudentByEmailResponse\x12d\n" +
	"\rUpdateStudent\x12(.course_recommender.UpdateStudentRequest\x1a).course_recommender.UpdateStudentResponse\x12a\n" +
	"\fListStudents\x12'.course_recommender.ListStudentsRequest\x1a(.course_recommender.ListStudentsResponse\x12d\n" +
	"\rDeleteStudent\x12(.course_recommender.DeleteStudentRequest\x1a).course_recommender.DeleteStudentResponse\x12v\n" +
	"\x13CreateStudentCourse\x12..course_recommender.CreateStudentCourseRequest\x1a/.course_recommender.CreateStudentCourseResponse\x12v\n" +
	"\x13UpdateStudentCourse\x12..course_recommender.UpdateStudentCourseRequest\x1a/.course_recommender.UpdateStudentCourseResponse\x12|\n" +
	"\x15GetStudentsByCourseId\x120.course_recommender.GetStudentsByCourseIdRequest\x1a1.course_recommender.GetStudentsByCourseIdResponse\x12|\n" +
	"\x15GetCoursesByStudentId\x120.course_recommender.GetCoursesByStudentIdRequest\x1a1.course_recommender.GetCoursesByStudentIdResponse\x12v\n" +
	"\x13DeleteStudentCourse\x12..course_recommender.DeleteStudentCourseRequest\x1a/.course_recommender.DeleteStudentCourseResponse\x12X\n" +
	"\tCreateTag\x12$.course_recommender.CreateTagRequest\x1a%.course_recommender.CreateTagResponse\x12O\n" +
	"\x06GetTag\x12!.course_recommender.GetTagRequest\x1a\".course_recommender.GetTagResponse\x12a\n" +
	"\fGetTagByName\x12'.course_recommender.GetTagByNameRequest\x1a(.course_recommender.GetTagByNameResponse\x12X\n" +
	"\tUpdateTag\x12$.course_recommender.UpdateTagRequest\x1a%.course_recommender.UpdateTagResponse\x12U\n" +
	"\bListTags\x12#.course_recommender.ListTagsRequest\x1a$.course_recommender.ListTagsResponse\x12X\n" +
	"\tDeleteTag\x12$.course_recommender.DeleteTagRequest\x1a%.course_recommender.DeleteTagResponseB\aZ\x05./apib\x06proto3"

var file_root_proto_goTypes = []any{
	(*CreateCourseRequest)(nil),                  // 0: course_recommender.CreateCourseRequest
	(*GetCourseRequest)(nil),                     // 1: course_recommender.GetCourseRequest
	(*GetCourseByNameRequest)(nil),               // 2: course_recommender.GetCourseByNameRequest
	(*UpdateCourseRequest)(nil),                  // 3: course_recommender.UpdateCourseRequest
	(*ListCoursesRequest)(nil),                   // 4: course_recommender.ListCoursesRequest
	(*DeleteCourseRequest)(nil),                  // 5: course_recommender.DeleteCourseRequest
	(*CreateCourseQuestionRequest)(nil),          // 6: course_recommender.CreateCourseQuestionRequest
	(*GetCourseQuestionRequest)(nil),             // 7: course_recommender.GetCourseQuestionRequest
	(*UpdateCourseQuestionRequest)(nil),          // 8: course_recommender.UpdateCourseQuestionRequest
	(*ListCourseQuestionsRequest)(nil),           // 9: course_recommender.ListCourseQuestionsRequest
	(*DeleteCourseQuestionRequest)(nil),          // 10: course_recommender.DeleteCourseQuestionRequest
	(*GetCourseQuestionsByCourseIdRequest)(nil),  // 11: course_recommender.GetCourseQuestionsByCourseIdRequest
	(*CreateCourseTagRequest)(nil),               // 12: course_recommender.CreateCourseTagRequest
	(*GetTagsByCourseIdRequest)(nil),             // 13: course_recommender.GetTagsByCourseIdRequest
	(*GetCoursesByTagIdRequest)(nil),             // 14: course_recommender.GetCoursesByTagIdRequest
	(*DeleteCourseTagRequest)(nil),               // 15: course_recommender.DeleteCourseTagRequest
	(*CreateDegreeCourseRequest)(nil),            // 16: course_recommender.CreateDegreeCourseRequest
	(*GetCoursesByDegreeIdRequest)(nil),          // 17: course_recommender.GetCoursesByDegreeIdRequest
	(*GetDegreesByCourseIdRequest)(nil),          // 18: course_recommender.GetDegreesByCourseIdRequest
	(*DeleteDegreeCourseRequest)(nil),            // 19: course_recommender.DeleteDegreeCourseRequest
	(*CreateDegreeTypeRequest)(nil),              // 20: course_recommender.CreateDegreeTypeRequest
	(*GetDegreeTypeRequest)(nil),                 // 21: course_recommender.GetDegreeTypeRequest
	(*GetDegreeTypeByNameRequest)(nil),           // 22: course_recommender.GetDegreeTypeByNameRequest
	(*UpdateDegreeTypeRequest)(nil),              // 23: course_recommender.UpdateDegreeTypeRequest
	(*ListDegreeTypesRequest)(nil),               // 24: course_recommender.ListDegreeTypesRequest
	(*DeleteDegreeTypeRequest)(nil),              // 25: course_recommender.DeleteDegreeTypeRequest
	(*CreateStudentRequest)(nil),                 // 26: course_recommender.CreateStudentRequest
	(*GetStudentRequest)(nil),                    // 27: course_recommender.GetStudentRequest
	(*GetStudentByEmailRequest)(nil),             // 28: course_recommender.GetStudentByEmailRequest
	(*UpdateStudentRequest)(nil),                 // 29: course_recommender.UpdateStudentRequest
	(*ListStudentsRequest)(nil),                  // 30: course_recommender.ListStudentsRequest
	(*DeleteStudentRequest)(nil),                 // 31: course_recommender.DeleteStudentRequest
	(*CreateStudentCourseRequest)(nil),           // 32: course_recommender.CreateStudentCourseRequest
	(*UpdateStudentCourseRequest)(nil),           // 33: course_recommender.UpdateStudentCourseRequest
	(*GetStudentsByCourseIdRequest)(nil),         // 34: course_recommender.GetStudentsByCourseIdRequest
	(*GetCoursesByStudentIdRequest)(nil),         // 35: course_recommender.GetCoursesByStudentIdRequest
	(*DeleteStudentCourseRequest)(nil),           // 36: course_recommender.DeleteStudentCourseRequest
	(*CreateTagRequest)(nil),                     // 37: course_recommender.CreateTagRequest
	(*GetTagRequest)(nil),                        // 38: course_recommender.GetTagRequest
	(*GetTagByNameRequest)(nil),                  // 39: course_recommender.GetTagByNameRequest
	(*UpdateTagRequest)(nil),                     // 40: course_recommender.UpdateTagRequest
	(*ListTagsRequest)(nil),                      // 41: course_recommender.ListTagsRequest
	(*DeleteTagRequest)(nil),                     // 42: course_recommender.DeleteTagRequest
	(*CreateCourseResponse)(nil),                 // 43: course_recommender.CreateCourseResponse
	(*GetCourseResponse)(nil),                    // 44: course_recommender.GetCourseResponse
	(*GetCourseByNameResponse)(nil),              // 45: course_recommender.GetCourseByNameResponse
	(*UpdateCourseResponse)(nil),                 // 46: course_recommender.UpdateCourseResponse
	(*ListCoursesResponse)(nil),                  // 47: course_recommender.ListCoursesResponse
	(*DeleteCourseResponse)(nil),                 // 48: course_recommender.DeleteCourseResponse
	(*CreateCourseQuestionResponse)(nil),         // 49: course_recommender.CreateCourseQuestionResponse
	(*GetCourseQuestionResponse)(nil),            // 50: course_recommender.GetCourseQuestionResponse
	(*UpdateCourseQuestionResponse)(nil),         // 51: course_recommender.UpdateCourseQuestionResponse
	(*ListCourseQuestionsResponse)(nil),          // 52: course_recommender.ListCourseQuestionsResponse
	(*DeleteCourseQuestionResponse)(nil),         // 53: course_recommender.DeleteCourseQuestionResponse
	(*GetCourseQuestionsByCourseIdResponse)(nil), // 54: course_recommender.GetCourseQuestionsByCourseIdResponse
	(*CreateCourseTagResponse)(nil),              // 55: course_recommender.CreateCourseTagResponse
	(*GetTagsByCourseIdResponse)(nil),            // 56: course_recommender.GetTagsByCourseIdResponse
	(*GetCoursesByTagIdResponse)(nil),            // 57: course_recommender.GetCoursesByTagIdResponse
	(*DeleteCourseTagResponse)(nil),              // 58: course_recommender.DeleteCourseTagResponse
	(*CreateDegreeCourseResponse)(nil),           // 59: course_recommender.CreateDegreeCourseResponse
	(*GetCoursesByDegreeIdResponse)(nil),         // 60: course_recommender.GetCoursesByDegreeIdResponse
	(*GetDegreesByCourseIdResponse)(nil),         // 61: course_recommender.GetDegreesByCourseIdResponse
	(*DeleteDegreeCourseResponse)(nil),           // 62: course_recommender.DeleteDegreeCourseResponse
	(*CreateDegreeTypeResponse)(nil),             // 63: course_recommender.CreateDegreeTypeResponse
	(*GetDegreeTypeResponse)(nil),                // 64: course_recommender.GetDegreeTypeResponse
	(*GetDegreeTypeByNameResponse)(nil),          // 65: course_recommender.GetDegreeTypeByNameResponse
	(*UpdateDegreeTypeResponse)(nil),             // 66: course_recommender.UpdateDegreeTypeResponse
	(*ListDegreeTypesResponse)(nil),              // 67: course_recommender.ListDegreeTypesResponse
	(*DeleteDegreeTypeResponse)(nil),             // 68: course_recommender.DeleteDegreeTypeResponse
	(*CreateStudentResponse)(nil),                // 69: course_recommender.CreateStudentResponse
	(*GetStudentResponse)(nil),                   // 70: course_recommender.GetStudentResponse
	(*GetStudentByEmailResponse)(nil),            // 71: course_recommender.GetStudentByEmailResponse
	(*UpdateStudentResponse)(nil),                // 72: course_recommender.UpdateStudentResponse
	(*ListStudentsResponse)(nil),                 // 73: course_recommender.ListStudentsResponse
	(*DeleteStudentResponse)(nil),                // 74: course_recommender.DeleteStudentResponse
	(*CreateStudentCourseResponse)(nil),          // 75: course_recommender.CreateStudentCourseResponse
	(*UpdateStudentCourseResponse)(nil),          // 76: course_recommender.UpdateStudentCourseResponse
	(*GetStudentsByCourseIdResponse)(nil),        // 77: course_recommender.GetStudentsByCourseIdResponse
	(*GetCoursesByStudentIdResponse)(nil),        // 78: course_recommender.GetCoursesByStudentIdResponse
	(*DeleteStudentCourseResponse)(nil),          // 79: course_recommender.DeleteStudentCourseResponse
	(*CreateTagResponse)(nil),                    // 80: course_recommender.CreateTagResponse
	(*GetTagResponse)(nil),                       // 81: course_recommender.GetTagResponse
	(*GetTagByNameResponse)(nil),                 // 82: course_recommender.GetTagByNameResponse
	(*UpdateTagResponse)(nil),                    // 83: course_recommender.UpdateTagResponse
	(*ListTagsResponse)(nil),                     // 84: course_recommender.ListTagsResponse
	(*DeleteTagResponse)(nil),                    // 85: course_recommender.DeleteTagResponse
}
var file_root_proto_depIdxs = []int32{
	0,  // 0: course_recommender.CourseRecommenderService.CreateCourse:input_type -> course_recommender.CreateCourseRequest
	1,  // 1: course_recommender.CourseRecommenderService.GetCourse:input_type -> course_recommender.GetCourseRequest
	2,  // 2: course_recommender.CourseRecommenderService.GetCourseByName:input_type -> course_recommender.GetCourseByNameRequest
	3,  // 3: course_recommender.CourseRecommenderService.UpdateCourse:input_type -> course_recommender.UpdateCourseRequest
	4,  // 4: course_recommender.CourseRecommenderService.ListCourses:input_type -> course_recommender.ListCoursesRequest
	5,  // 5: course_recommender.CourseRecommenderService.DeleteCourse:input_type -> course_recommender.DeleteCourseRequest
	6,  // 6: course_recommender.CourseRecommenderService.CreateCourseQuestion:input_type -> course_recommender.CreateCourseQuestionRequest
	7,  // 7: course_recommender.CourseRecommenderService.GetCourseQuestion:input_type -> course_recommender.GetCourseQuestionRequest
	8,  // 8: course_recommender.CourseRecommenderService.UpdateCourseQuestion:input_type -> course_recommender.UpdateCourseQuestionRequest
	9,  // 9: course_recommender.CourseRecommenderService.ListCourseQuestions:input_type -> course_recommender.ListCourseQuestionsRequest
	10, // 10: course_recommender.CourseRecommenderService.DeleteCourseQuestion:input_type -> course_recommender.DeleteCourseQuestionRequest
	11, // 11: course_recommender.CourseRecommenderService.GetCourseQuestionsByCourseId:input_type -> course_recommender.GetCourseQuestionsByCourseIdRequest
	12, // 12: course_recommender.CourseRecommenderService.CreateCourseTag:input_type -> course_recommender.CreateCourseTagRequest
	13, // 13: course_recommender.CourseRecommenderService.GetTagsByCourseId:input_type -> course_recommender.GetTagsByCourseIdRequest
	14, // 14: course_recommender.CourseRecommenderService.GetCoursesByTagId:input_type -> course_recommender.GetCoursesByTagIdRequest
	15, // 15: course_recommender.CourseRecommenderService.DeleteCourseTag:input_type -> course_recommender.DeleteCourseTagRequest
	16, // 16: course_recommender.CourseRecommenderService.CreateDegreeCourse:input_type -> course_recommender.CreateDegreeCourseRequest
	17, // 17: course_recommender.CourseRecommenderService.GetCoursesByDegreeId:input_type -> course_recommender.GetCoursesByDegreeIdRequest
	18, // 18: course_recommender.CourseRecommenderService.GetDegreesByCourseId:input_type -> course_recommender.GetDegreesByCourseIdRequest
	19, // 19: course_recommender.CourseRecommenderService.DeleteDegreeCourse:input_type -> course_recommender.DeleteDegreeCourseRequest
	20, // 20: course_recommender.CourseRecommenderService.CreateDegreeType:input_type -> course_recommender.CreateDegreeTypeRequest
	21, // 21: course_recommender.CourseRecommenderService.GetDegreeType:input_type -> course_recommender.GetDegreeTypeRequest
	22, // 22: course_recommender.CourseRecommenderService.GetDegreeTypeByName:input_type -> course_recommender.GetDegreeTypeByNameRequest
	23, // 23: course_recommender.CourseRecommenderService.UpdateDegreeType:input_type -> course_recommender.UpdateDegreeTypeRequest
	24, // 24: course_recommender.CourseRecommenderService.ListDegreeTypes:input_type -> course_recommender.ListDegreeTypesRequest
	25, // 25: course_recommender.CourseRecommenderService.DeleteDegreeType:input_type -> course_recommender.DeleteDegreeTypeRequest
	26, // 26: course_recommender.CourseRecommenderService.CreateStudent:input_type -> course_recommender.CreateStudentRequest
	27, // 27: course_recommender.CourseRecommenderService.GetStudent:input_type -> course_recommender.GetStudentRequest
	28, // 28: course_recommender.CourseRecommenderService.GetStudentByEmail:input_type -> course_recommender.GetStudentByEmailRequest
	29, // 29: course_recommender.CourseRecommenderService.UpdateStudent:input_type -> course_recommender.UpdateStudentRequest
	30, // 30: course_recommender.CourseRecommenderService.ListStudents:input_type -> course_recommender.ListStudentsRequest
	31, // 31: course_recommender.CourseRecommenderService.DeleteStudent:input_type -> course_recommender.DeleteStudentRequest
	32, // 32: course_recommender.CourseRecommenderService.CreateStudentCourse:input_type -> course_recommender.CreateStudentCourseRequest
	33, // 33: course_recommender.CourseRecommenderService.UpdateStudentCourse:input_type -> course_recommender.UpdateStudentCourseRequest
	34, // 34: course_recommender.CourseRecommenderService.GetStudentsByCourseId:input_type -> course_recommender.GetStudentsByCourseIdRequest
	35, // 35: course_recommender.CourseRecommenderService.GetCoursesByStudentId:input_type -> course_recommender.GetCoursesByStudentIdRequest
	36, // 36: course_recommender.CourseRecommenderService.DeleteStudentCourse:input_type -> course_recommender.DeleteStudentCourseRequest
	37, // 37: course_recommender.CourseRecommenderService.CreateTag:input_type -> course_recommender.CreateTagRequest
	38, // 38: course_recommender.CourseRecommenderService.GetTag:input_type -> course_recommender.GetTagRequest
	39, // 39: course_recommender.CourseRecommenderService.GetTagByName:input_type -> course_recommender.GetTagByNameRequest
	40, // 40: course_recommender.CourseRecommenderService.UpdateTag:input_type -> course_recommender.UpdateTagRequest
	41, // 41: course_recommender.CourseRecommenderService.ListTags:input_type -> course_recommender.ListTagsRequest
	42, // 42: course_recommender.CourseRecommenderService.DeleteTag:input_type -> course_recommender.DeleteTagRequest
	43, // 43: course_recommender.CourseRecommenderService.CreateCourse:output_type -> course_recommender.CreateCourseResponse
	44, // 44: course_recommender.CourseRecommenderService.GetCourse:output_type -> course_recommender.GetCourseResponse
	45, // 45: course_recommender.CourseRecommenderService.GetCourseByName:output_type -> course_recommender.GetCourseByNameResponse
	46, // 46: course_recommender.CourseRecommenderService.UpdateCourse:output_type -> course_recommender.UpdateCourseResponse
	47, // 47: course_recommender.CourseRecommenderService.ListCourses:output_type -> course_recommender.ListCoursesResponse
	48, // 48: course_recommender.CourseRecommenderService.DeleteCourse:output_type -> course_recommender.DeleteCourseResponse
	49, // 49: course_recommender.CourseRecommenderService.CreateCourseQuestion:output_type -> course_recommender.CreateCourseQuestionResponse
	50, // 50: course_recommender.CourseRecommenderService.GetCourseQuestion:output_type -> course_recommender.GetCourseQuestionResponse
	51, // 51: course_recommender.CourseRecommenderService.UpdateCourseQuestion:output_type -> course_recommender.UpdateCourseQuestionResponse
	52, // 52: course_recommender.CourseRecommenderService.ListCourseQuestions:output_type -> course_recommender.ListCourseQuestionsResponse
	53, // 53: course_recommender.CourseRecommenderService.DeleteCourseQuestion:output_type -> course_recommender.DeleteCourseQuestionResponse
	54, // 54: course_recommender.CourseRecommenderService.GetCourseQuestionsByCourseId:output_type -> course_recommender.GetCourseQuestionsByCourseIdResponse
	55, // 55: course_recommender.CourseRecommenderService.CreateCourseTag:output_type -> course_recommender.CreateCourseTagResponse
	56, // 56: course_recommender.CourseRecommenderService.GetTagsByCourseId:output_type -> course_recommender.GetTagsByCourseIdResponse
	57, // 57: course_recommender.CourseRecommenderService.GetCoursesByTagId:output_type -> course_recommender.GetCoursesByTagIdResponse
	58, // 58: course_recommender.CourseRecommenderService.DeleteCourseTag:output_type -> course_recommender.DeleteCourseTagResponse
	59, // 59: course_recommender.CourseRecommenderService.CreateDegreeCourse:output_type -> course_recommender.CreateDegreeCourseResponse
	60, // 60: course_recommender.CourseRecommenderService.GetCoursesByDegreeId:output_type -> course_recommender.GetCoursesByDegreeIdResponse
	61, // 61: course_recommender.CourseRecommenderService.GetDegreesByCourseId:output_type -> course_recommender.GetDegreesByCourseIdResponse
	62, // 62: course_recommender.CourseRecommenderService.DeleteDegreeCourse:output_type -> course_recommender.DeleteDegreeCourseResponse
	63, // 63: course_recommender.CourseRecommenderService.CreateDegreeType:output_type -> course_recommender.CreateDegreeTypeResponse
	64, // 64: course_recommender.CourseRecommenderService.GetDegreeType:output_type -> course_recommender.GetDegreeTypeResponse
	65, // 65: course_recommender.CourseRecommenderService.GetDegreeTypeByName:output_type -> course_recommender.GetDegreeTypeByNameResponse
	66, // 66: course_recommender.CourseRecommenderService.UpdateDegreeType:output_type -> course_recommender.UpdateDegreeTypeResponse
	67, // 67: course_recommender.CourseRecommenderService.ListDegreeTypes:output_type -> course_recommender.ListDegreeTypesResponse
	68, // 68: course_recommender.CourseRecommenderService.DeleteDegreeType:output_type -> course_recommender.DeleteDegreeTypeResponse
	69, // 69: course_recommender.CourseRecommenderService.CreateStudent:output_type -> course_recommender.CreateStudentResponse
	70, // 70: course_recommender.CourseRecommenderService.GetStudent:output_type -> course_recommender.GetStudentResponse
	71, // 71: course_recommender.CourseRecommenderService.GetStudentByEmail:output_type -> course_recommender.GetStudentByEmailResponse
	72, // 72: course_recommender.CourseRecommenderService.UpdateStudent:output_type -> course_recommender.UpdateStudentResponse
	73, // 73: course_recommender.CourseRecommenderService.ListStudents:output_type -> course_recommender.ListStudentsResponse
	74, // 74: course_recommender.CourseRecommenderService.DeleteStudent:output_type -> course_recommender.DeleteStudentResponse
	75, // 75: course_recommender.CourseRecommenderService.CreateStudentCourse:output_type -> course_recommender.CreateStudentCourseResponse
	76, // 76: course_recommender.CourseRecommenderService.UpdateStudentCourse:output_type -> course_recommender.UpdateStudentCourseResponse
	77, // 77: course_recommender.CourseRecommenderService.GetStudentsByCourseId:output_type -> course_recommender.GetStudentsByCourseIdResponse
	78, // 78: course_recommender.CourseRecommenderService.GetCoursesByStudentId:output_type -> course_recommender.GetCoursesByStudentIdResponse
	79, // 79: course_recommender.CourseRecommenderService.DeleteStudentCourse:output_type -> course_recommender.DeleteStudentCourseResponse
	80, // 80: course_recommender.CourseRecommenderService.CreateTag:output_type -> course_recommender.CreateTagResponse
	81, // 81: course_recommender.CourseRecommenderService.GetTag:output_type -> course_recommender.GetTagResponse
	82, // 82: course_recommender.CourseRecommenderService.GetTagByName:output_type -> course_recommender.GetTagByNameResponse
	83, // 83: course_recommender.CourseRecommenderService.UpdateTag:output_type -> course_recommender.UpdateTagResponse
	84, // 84: course_recommender.CourseRecommenderService.ListTags:output_type -> course_recommender.ListTagsResponse
	85, // 85: course_recommender.CourseRecommenderService.DeleteTag:output_type -> course_recommender.DeleteTagResponse
	43, // [43:86] is the sub-list for method output_type
	0,  // [0:43] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_root_proto_init() }
func file_root_proto_init() {
	if File_root_proto != nil {
		return
	}
	file_course_proto_init()
	file_course_question_proto_init()
	file_course_tag_proto_init()
	file_degree_course_proto_init()
	file_degree_type_proto_init()
	file_student_proto_init()
	file_student_course_proto_init()
	file_tag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_root_proto_rawDesc), len(file_root_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_root_proto_goTypes,
		DependencyIndexes: file_root_proto_depIdxs,
	}.Build()
	File_root_proto = out.File
	file_root_proto_goTypes = nil
	file_root_proto_depIdxs = nil
}
