// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: student.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The main Student message, representing a student in the database.
// Note: Exposing password fields in APIs should be handled with care.
type Student struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentUsername string                 `protobuf:"bytes,2,opt,name=student_username,json=studentUsername,proto3" json:"student_username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetStudentUsername() string {
	if x != nil {
		return x.StudentUsername
	}
	return ""
}

// Request to create a new student.
type CreateStudentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentUsername string                 `protobuf:"bytes,1,opt,name=student_username,json=studentUsername,proto3" json:"student_username,omitempty"`
	StudentPassword string                 `protobuf:"bytes,2,opt,name=student_password,json=studentPassword,proto3" json:"student_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStudentRequest) GetStudentUsername() string {
	if x != nil {
		return x.StudentUsername
	}
	return ""
}

func (x *CreateStudentRequest) GetStudentPassword() string {
	if x != nil {
		return x.StudentPassword
	}
	return ""
}

// Response containing the newly created student.
type CreateStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentResponse) Reset() {
	*x = CreateStudentResponse{}
	mi := &file_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentResponse) ProtoMessage() {}

func (x *CreateStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentResponse.ProtoReflect.Descriptor instead.
func (*CreateStudentResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

// Request to get a student by their ID.
type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response containing the requested student.
type GetStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentResponse) Reset() {
	*x = GetStudentResponse{}
	mi := &file_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentResponse) ProtoMessage() {}

func (x *GetStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentResponse.ProtoReflect.Descriptor instead.
func (*GetStudentResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

// Request to get a student by username and password
type GetStudentByUsernameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentUsername string                 `protobuf:"bytes,1,opt,name=student_username,json=studentUsername,proto3" json:"student_username,omitempty"`
	StudentPassword string                 `protobuf:"bytes,2,opt,name=student_password,json=studentPassword,proto3" json:"student_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStudentByUsernameRequest) Reset() {
	*x = GetStudentByUsernameRequest{}
	mi := &file_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentByUsernameRequest) ProtoMessage() {}

func (x *GetStudentByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetStudentByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{5}
}

func (x *GetStudentByUsernameRequest) GetStudentUsername() string {
	if x != nil {
		return x.StudentUsername
	}
	return ""
}

func (x *GetStudentByUsernameRequest) GetStudentPassword() string {
	if x != nil {
		return x.StudentPassword
	}
	return ""
}

// Response containing the requested student.
type GetStudentByUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentByUsernameResponse) Reset() {
	*x = GetStudentByUsernameResponse{}
	mi := &file_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentByUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentByUsernameResponse) ProtoMessage() {}

func (x *GetStudentByUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentByUsernameResponse.ProtoReflect.Descriptor instead.
func (*GetStudentByUsernameResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{6}
}

func (x *GetStudentByUsernameResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

// Request to update an existing student's information.
type UpdateStudentRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentUsername *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=student_username,json=studentUsername,proto3" json:"student_username,omitempty"`
	StudentPassword *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=student_password,json=studentPassword,proto3" json:"student_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateStudentRequest) Reset() {
	*x = UpdateStudentRequest{}
	mi := &file_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentRequest) ProtoMessage() {}

func (x *UpdateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStudentRequest) GetStudentUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.StudentUsername
	}
	return nil
}

func (x *UpdateStudentRequest) GetStudentPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.StudentPassword
	}
	return nil
}

// Response containing the updated student.
type UpdateStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentResponse) Reset() {
	*x = UpdateStudentResponse{}
	mi := &file_student_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentResponse) ProtoMessage() {}

func (x *UpdateStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentResponse.ProtoReflect.Descriptor instead.
func (*UpdateStudentResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

// Request to list all students.
type ListStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsRequest) Reset() {
	*x = ListStudentsRequest{}
	mi := &file_student_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsRequest) ProtoMessage() {}

func (x *ListStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsRequest.ProtoReflect.Descriptor instead.
func (*ListStudentsRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{9}
}

// Response containing a list of all students.
type ListStudentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsResponse) Reset() {
	*x = ListStudentsResponse{}
	mi := &file_student_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsResponse) ProtoMessage() {}

func (x *ListStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsResponse.ProtoReflect.Descriptor instead.
func (*ListStudentsResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{10}
}

func (x *ListStudentsResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

// Request to delete a student by their ID.
type DeleteStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentRequest) Reset() {
	*x = DeleteStudentRequest{}
	mi := &file_student_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentRequest) ProtoMessage() {}

func (x *DeleteStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response indicating whether the deletion was successful.
type DeleteStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentResponse) Reset() {
	*x = DeleteStudentResponse{}
	mi := &file_student_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentResponse) ProtoMessage() {}

func (x *DeleteStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentResponse.ProtoReflect.Descriptor instead.
func (*DeleteStudentResponse) Descriptor() ([]byte, []int) {
	return file_student_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteStudentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_student_proto protoreflect.FileDescriptor

const file_student_proto_rawDesc = "" +
	"\n" +
	"\rstudent.proto\x12\x12course_recommender\x1a\x1egoogle/protobuf/wrappers.proto\"D\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\x10student_username\x18\x02 \x01(\tR\x0fstudentUsername\"l\n" +
	"\x14CreateStudentRequest\x12)\n" +
	"\x10student_username\x18\x01 \x01(\tR\x0fstudentUsername\x12)\n" +
	"\x10student_password\x18\x02 \x01(\tR\x0fstudentPassword\"N\n" +
	"\x15CreateStudentResponse\x125\n" +
	"\astudent\x18\x01 \x01(\v2\x1b.course_recommender.StudentR\astudent\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x12GetStudentResponse\x125\n" +
	"\astudent\x18\x01 \x01(\v2\x1b.course_recommender.StudentR\astudent\"s\n" +
	"\x1bGetStudentByUsernameRequest\x12)\n" +
	"\x10student_username\x18\x01 \x01(\tR\x0fstudentUsername\x12)\n" +
	"\x10student_password\x18\x02 \x01(\tR\x0fstudentPassword\"U\n" +
	"\x1cGetStudentByUsernameResponse\x125\n" +
	"\astudent\x18\x01 \x01(\v2\x1b.course_recommender.StudentR\astudent\"\xb8\x01\n" +
	"\x14UpdateStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12G\n" +
	"\x10student_username\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x0fstudentUsername\x12G\n" +
	"\x10student_password\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x0fstudentPassword\"N\n" +
	"\x15UpdateStudentResponse\x125\n" +
	"\astudent\x18\x01 \x01(\v2\x1b.course_recommender.StudentR\astudent\"\x15\n" +
	"\x13ListStudentsRequest\"O\n" +
	"\x14ListStudentsResponse\x127\n" +
	"\bstudents\x18\x01 \x03(\v2\x1b.course_recommender.StudentR\bstudents\"&\n" +
	"\x14DeleteStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x15DeleteStudentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\aZ\x05./apib\x06proto3"

var (
	file_student_proto_rawDescOnce sync.Once
	file_student_proto_rawDescData []byte
)

func file_student_proto_rawDescGZIP() []byte {
	file_student_proto_rawDescOnce.Do(func() {
		file_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_proto_rawDesc), len(file_student_proto_rawDesc)))
	})
	return file_student_proto_rawDescData
}

var file_student_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_student_proto_goTypes = []any{
	(*Student)(nil),                      // 0: course_recommender.Student
	(*CreateStudentRequest)(nil),         // 1: course_recommender.CreateStudentRequest
	(*CreateStudentResponse)(nil),        // 2: course_recommender.CreateStudentResponse
	(*GetStudentRequest)(nil),            // 3: course_recommender.GetStudentRequest
	(*GetStudentResponse)(nil),           // 4: course_recommender.GetStudentResponse
	(*GetStudentByUsernameRequest)(nil),  // 5: course_recommender.GetStudentByUsernameRequest
	(*GetStudentByUsernameResponse)(nil), // 6: course_recommender.GetStudentByUsernameResponse
	(*UpdateStudentRequest)(nil),         // 7: course_recommender.UpdateStudentRequest
	(*UpdateStudentResponse)(nil),        // 8: course_recommender.UpdateStudentResponse
	(*ListStudentsRequest)(nil),          // 9: course_recommender.ListStudentsRequest
	(*ListStudentsResponse)(nil),         // 10: course_recommender.ListStudentsResponse
	(*DeleteStudentRequest)(nil),         // 11: course_recommender.DeleteStudentRequest
	(*DeleteStudentResponse)(nil),        // 12: course_recommender.DeleteStudentResponse
	(*wrapperspb.StringValue)(nil),       // 13: google.protobuf.StringValue
}
var file_student_proto_depIdxs = []int32{
	0,  // 0: course_recommender.CreateStudentResponse.student:type_name -> course_recommender.Student
	0,  // 1: course_recommender.GetStudentResponse.student:type_name -> course_recommender.Student
	0,  // 2: course_recommender.GetStudentByUsernameResponse.student:type_name -> course_recommender.Student
	13, // 3: course_recommender.UpdateStudentRequest.student_username:type_name -> google.protobuf.StringValue
	13, // 4: course_recommender.UpdateStudentRequest.student_password:type_name -> google.protobuf.StringValue
	0,  // 5: course_recommender.UpdateStudentResponse.student:type_name -> course_recommender.Student
	0,  // 6: course_recommender.ListStudentsResponse.students:type_name -> course_recommender.Student
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_student_proto_init() }
func file_student_proto_init() {
	if File_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_proto_rawDesc), len(file_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_student_proto_goTypes,
		DependencyIndexes: file_student_proto_depIdxs,
		MessageInfos:      file_student_proto_msgTypes,
	}.Build()
	File_student_proto = out.File
	file_student_proto_goTypes = nil
	file_student_proto_depIdxs = nil
}
