// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: student_course.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The StudentCourse message, representing the many-to-many relationship
// between students and courses, including marks and feedback.
type StudentCourse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Marks         int32                  `protobuf:"varint,3,opt,name=marks,proto3" json:"marks,omitempty"`
	Feedback      bool                   `protobuf:"varint,4,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentCourse) Reset() {
	*x = StudentCourse{}
	mi := &file_student_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentCourse) ProtoMessage() {}

func (x *StudentCourse) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentCourse.ProtoReflect.Descriptor instead.
func (*StudentCourse) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{0}
}

func (x *StudentCourse) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *StudentCourse) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *StudentCourse) GetMarks() int32 {
	if x != nil {
		return x.Marks
	}
	return 0
}

func (x *StudentCourse) GetFeedback() bool {
	if x != nil {
		return x.Feedback
	}
	return false
}

// Request to create a new student-course association (enrollment).
type CreateStudentCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentCourseRequest) Reset() {
	*x = CreateStudentCourseRequest{}
	mi := &file_student_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentCourseRequest) ProtoMessage() {}

func (x *CreateStudentCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentCourseRequest) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStudentCourseRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *CreateStudentCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response containing the newly created student-course association.
type CreateStudentCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentCourse *StudentCourse         `protobuf:"bytes,1,opt,name=student_course,json=studentCourse,proto3" json:"student_course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentCourseResponse) Reset() {
	*x = CreateStudentCourseResponse{}
	mi := &file_student_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentCourseResponse) ProtoMessage() {}

func (x *CreateStudentCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateStudentCourseResponse) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentCourseResponse) GetStudentCourse() *StudentCourse {
	if x != nil {
		return x.StudentCourse
	}
	return nil
}

// Request to update a student's marks and feedback for a course.
type UpdateStudentCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Marks         *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=marks,proto3" json:"marks,omitempty"`
	Feedback      *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentCourseRequest) Reset() {
	*x = UpdateStudentCourseRequest{}
	mi := &file_student_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentCourseRequest) ProtoMessage() {}

func (x *UpdateStudentCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentCourseRequest) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStudentCourseRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *UpdateStudentCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *UpdateStudentCourseRequest) GetMarks() *wrapperspb.Int32Value {
	if x != nil {
		return x.Marks
	}
	return nil
}

func (x *UpdateStudentCourseRequest) GetFeedback() *wrapperspb.BoolValue {
	if x != nil {
		return x.Feedback
	}
	return nil
}

// Response containing the updated student-course association.
type UpdateStudentCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentCourse *StudentCourse         `protobuf:"bytes,1,opt,name=student_course,json=studentCourse,proto3" json:"student_course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentCourseResponse) Reset() {
	*x = UpdateStudentCourseResponse{}
	mi := &file_student_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentCourseResponse) ProtoMessage() {}

func (x *UpdateStudentCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateStudentCourseResponse) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStudentCourseResponse) GetStudentCourse() *StudentCourse {
	if x != nil {
		return x.StudentCourse
	}
	return nil
}

// Request to get all students enrolled in a specific course.
type GetStudentsByCourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentsByCourseIdRequest) Reset() {
	*x = GetStudentsByCourseIdRequest{}
	mi := &file_student_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentsByCourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsByCourseIdRequest) ProtoMessage() {}

func (x *GetStudentsByCourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsByCourseIdRequest.ProtoReflect.Descriptor instead.
func (*GetStudentsByCourseIdRequest) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{5}
}

func (x *GetStudentsByCourseIdRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response containing a list of students for a specific course.
type GetStudentsByCourseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentsByCourseIdResponse) Reset() {
	*x = GetStudentsByCourseIdResponse{}
	mi := &file_student_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentsByCourseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsByCourseIdResponse) ProtoMessage() {}

func (x *GetStudentsByCourseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsByCourseIdResponse.ProtoReflect.Descriptor instead.
func (*GetStudentsByCourseIdResponse) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{6}
}

func (x *GetStudentsByCourseIdResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

// Request to get all courses a specific student is enrolled in.
type GetCoursesByStudentIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesByStudentIdRequest) Reset() {
	*x = GetCoursesByStudentIdRequest{}
	mi := &file_student_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesByStudentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesByStudentIdRequest) ProtoMessage() {}

func (x *GetCoursesByStudentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesByStudentIdRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesByStudentIdRequest) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{7}
}

func (x *GetCoursesByStudentIdRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

// Response containing a list of courses for a specific student.
type GetCoursesByStudentIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesByStudentIdResponse) Reset() {
	*x = GetCoursesByStudentIdResponse{}
	mi := &file_student_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesByStudentIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesByStudentIdResponse) ProtoMessage() {}

func (x *GetCoursesByStudentIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesByStudentIdResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesByStudentIdResponse) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{8}
}

func (x *GetCoursesByStudentIdResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

// Request to delete a student-course association.
type DeleteStudentCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int64                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentCourseRequest) Reset() {
	*x = DeleteStudentCourseRequest{}
	mi := &file_student_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentCourseRequest) ProtoMessage() {}

func (x *DeleteStudentCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentCourseRequest) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteStudentCourseRequest) GetStudentId() int64 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *DeleteStudentCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// Response indicating whether the deletion was successful.
type DeleteStudentCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentCourseResponse) Reset() {
	*x = DeleteStudentCourseResponse{}
	mi := &file_student_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentCourseResponse) ProtoMessage() {}

func (x *DeleteStudentCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_student_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteStudentCourseResponse) Descriptor() ([]byte, []int) {
	return file_student_course_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteStudentCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_student_course_proto protoreflect.FileDescriptor

const file_student_course_proto_rawDesc = "" +
	"\n" +
	"\x14student_course.proto\x12\x12course_recommender\x1a\x1egoogle/protobuf/wrappers.proto\x1a\rstudent.proto\x1a\fcourse.proto\"}\n" +
	"\rStudentCourse\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05marks\x18\x03 \x01(\x05R\x05marks\x12\x1a\n" +
	"\bfeedback\x18\x04 \x01(\bR\bfeedback\"X\n" +
	"\x1aCreateStudentCourseRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"g\n" +
	"\x1bCreateStudentCourseResponse\x12H\n" +
	"\x0estudent_course\x18\x01 \x01(\v2!.course_recommender.StudentCourseR\rstudentCourse\"\xc3\x01\n" +
	"\x1aUpdateStudentCourseRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x121\n" +
	"\x05marks\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05marks\x126\n" +
	"\bfeedback\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\bfeedback\"g\n" +
	"\x1bUpdateStudentCourseResponse\x12H\n" +
	"\x0estudent_course\x18\x01 \x01(\v2!.course_recommender.StudentCourseR\rstudentCourse\";\n" +
	"\x1cGetStudentsByCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"X\n" +
	"\x1dGetStudentsByCourseIdResponse\x127\n" +
	"\bstudents\x18\x01 \x03(\v2\x1b.course_recommender.StudentR\bstudents\"=\n" +
	"\x1cGetCoursesByStudentIdRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03R\tstudentId\"U\n" +
	"\x1dGetCoursesByStudentIdResponse\x124\n" +
	"\acourses\x18\x01 \x03(\v2\x1a.course_recommender.CourseR\acourses\"X\n" +
	"\x1aDeleteStudentCourseRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x03R\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"7\n" +
	"\x1bDeleteStudentCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfa\x04\n" +
	"\x14StudentCourseService\x12v\n" +
	"\x13CreateStudentCourse\x12..course_recommender.CreateStudentCourseRequest\x1a/.course_recommender.CreateStudentCourseResponse\x12v\n" +
	"\x13UpdateStudentCourse\x12..course_recommender.UpdateStudentCourseRequest\x1a/.course_recommender.UpdateStudentCourseResponse\x12|\n" +
	"\x15GetStudentsByCourseId\x120.course_recommender.GetStudentsByCourseIdRequest\x1a1.course_recommender.GetStudentsByCourseIdResponse\x12|\n" +
	"\x15GetCoursesByStudentId\x120.course_recommender.GetCoursesByStudentIdRequest\x1a1.course_recommender.GetCoursesByStudentIdResponse\x12v\n" +
	"\x13DeleteStudentCourse\x12..course_recommender.DeleteStudentCourseRequest\x1a/.course_recommender.DeleteStudentCourseResponseB\aZ\x05./apib\x06proto3"

var (
	file_student_course_proto_rawDescOnce sync.Once
	file_student_course_proto_rawDescData []byte
)

func file_student_course_proto_rawDescGZIP() []byte {
	file_student_course_proto_rawDescOnce.Do(func() {
		file_student_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_course_proto_rawDesc), len(file_student_course_proto_rawDesc)))
	})
	return file_student_course_proto_rawDescData
}

var file_student_course_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_student_course_proto_goTypes = []any{
	(*StudentCourse)(nil),                 // 0: course_recommender.StudentCourse
	(*CreateStudentCourseRequest)(nil),    // 1: course_recommender.CreateStudentCourseRequest
	(*CreateStudentCourseResponse)(nil),   // 2: course_recommender.CreateStudentCourseResponse
	(*UpdateStudentCourseRequest)(nil),    // 3: course_recommender.UpdateStudentCourseRequest
	(*UpdateStudentCourseResponse)(nil),   // 4: course_recommender.UpdateStudentCourseResponse
	(*GetStudentsByCourseIdRequest)(nil),  // 5: course_recommender.GetStudentsByCourseIdRequest
	(*GetStudentsByCourseIdResponse)(nil), // 6: course_recommender.GetStudentsByCourseIdResponse
	(*GetCoursesByStudentIdRequest)(nil),  // 7: course_recommender.GetCoursesByStudentIdRequest
	(*GetCoursesByStudentIdResponse)(nil), // 8: course_recommender.GetCoursesByStudentIdResponse
	(*DeleteStudentCourseRequest)(nil),    // 9: course_recommender.DeleteStudentCourseRequest
	(*DeleteStudentCourseResponse)(nil),   // 10: course_recommender.DeleteStudentCourseResponse
	(*wrapperspb.Int32Value)(nil),         // 11: google.protobuf.Int32Value
	(*wrapperspb.BoolValue)(nil),          // 12: google.protobuf.BoolValue
	(*Student)(nil),                       // 13: course_recommender.Student
	(*Course)(nil),                        // 14: course_recommender.Course
}
var file_student_course_proto_depIdxs = []int32{
	0,  // 0: course_recommender.CreateStudentCourseResponse.student_course:type_name -> course_recommender.StudentCourse
	11, // 1: course_recommender.UpdateStudentCourseRequest.marks:type_name -> google.protobuf.Int32Value
	12, // 2: course_recommender.UpdateStudentCourseRequest.feedback:type_name -> google.protobuf.BoolValue
	0,  // 3: course_recommender.UpdateStudentCourseResponse.student_course:type_name -> course_recommender.StudentCourse
	13, // 4: course_recommender.GetStudentsByCourseIdResponse.students:type_name -> course_recommender.Student
	14, // 5: course_recommender.GetCoursesByStudentIdResponse.courses:type_name -> course_recommender.Course
	1,  // 6: course_recommender.StudentCourseService.CreateStudentCourse:input_type -> course_recommender.CreateStudentCourseRequest
	3,  // 7: course_recommender.StudentCourseService.UpdateStudentCourse:input_type -> course_recommender.UpdateStudentCourseRequest
	5,  // 8: course_recommender.StudentCourseService.GetStudentsByCourseId:input_type -> course_recommender.GetStudentsByCourseIdRequest
	7,  // 9: course_recommender.StudentCourseService.GetCoursesByStudentId:input_type -> course_recommender.GetCoursesByStudentIdRequest
	9,  // 10: course_recommender.StudentCourseService.DeleteStudentCourse:input_type -> course_recommender.DeleteStudentCourseRequest
	2,  // 11: course_recommender.StudentCourseService.CreateStudentCourse:output_type -> course_recommender.CreateStudentCourseResponse
	4,  // 12: course_recommender.StudentCourseService.UpdateStudentCourse:output_type -> course_recommender.UpdateStudentCourseResponse
	6,  // 13: course_recommender.StudentCourseService.GetStudentsByCourseId:output_type -> course_recommender.GetStudentsByCourseIdResponse
	8,  // 14: course_recommender.StudentCourseService.GetCoursesByStudentId:output_type -> course_recommender.GetCoursesByStudentIdResponse
	10, // 15: course_recommender.StudentCourseService.DeleteStudentCourse:output_type -> course_recommender.DeleteStudentCourseResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_student_course_proto_init() }
func file_student_course_proto_init() {
	if File_student_course_proto != nil {
		return
	}
	file_student_proto_init()
	file_course_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_course_proto_rawDesc), len(file_student_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_student_course_proto_goTypes,
		DependencyIndexes: file_student_course_proto_depIdxs,
		MessageInfos:      file_student_course_proto_msgTypes,
	}.Build()
	File_student_course_proto = out.File
	file_student_course_proto_goTypes = nil
	file_student_course_proto_depIdxs = nil
}
