// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: course.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO
    course (course_name, difficulty)
VALUES
    ($1, $2)
RETURNING
    id, course_name, difficulty
`

type CreateCourseParams struct {
	CourseName string `json:"course_name"`
	Difficulty int16  `json:"difficulty"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse, arg.CourseName, arg.Difficulty)
	var i Course
	err := row.Scan(&i.ID, &i.CourseName, &i.Difficulty)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :one
DELETE FROM course
WHERE
    id = $1
RETURNING
    TRUE
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, deleteCourse, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getCourse = `-- name: GetCourse :one
SELECT
    id, course_name, difficulty
FROM
    course
WHERE
    id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(&i.ID, &i.CourseName, &i.Difficulty)
	return i, err
}

const getCourseByName = `-- name: GetCourseByName :many
SELECT
    id, course_name, difficulty
FROM
    course
WHERE
    id @@@ paradedb.match (
        'course_name',
        $1::TEXT,
        distance => 1
    )
ORDER BY
    paradedb.score (id) DESC
`

func (q *Queries) GetCourseByName(ctx context.Context, courseName string) ([]Course, error) {
	rows, err := q.db.Query(ctx, getCourseByName, courseName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(&i.ID, &i.CourseName, &i.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT
    id, course_name, difficulty
FROM
    course
ORDER BY
    difficulty ASC
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(&i.ID, &i.CourseName, &i.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE course
SET
    course_name = COALESCE($2, course_name),
    difficulty = COALESCE($3, difficulty)
WHERE
    id = $1
RETURNING
    id, course_name, difficulty
`

type UpdateCourseParams struct {
	ID         int64       `json:"id"`
	CourseName pgtype.Text `json:"course_name"`
	Difficulty pgtype.Int2 `json:"difficulty"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse, arg.ID, arg.CourseName, arg.Difficulty)
	var i Course
	err := row.Scan(&i.ID, &i.CourseName, &i.Difficulty)
	return i, err
}
