// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateCourseQuestion(ctx context.Context, arg CreateCourseQuestionParams) (CourseQuestion, error)
	CreateCourseTag(ctx context.Context, arg CreateCourseTagParams) (CourseTag, error)
	CreateDegreeCourse(ctx context.Context, arg CreateDegreeCourseParams) (DegreeCourse, error)
	CreateDegreeType(ctx context.Context, degreeName string) (DegreeType, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (CreateStudentRow, error)
	CreateStudentCourse(ctx context.Context, arg CreateStudentCourseParams) (StudentCourse, error)
	CreateTag(ctx context.Context, tagName string) (Tag, error)
	DeleteCourse(ctx context.Context, id int64) (bool, error)
	DeleteCourseQuestion(ctx context.Context, id int64) (bool, error)
	DeleteCourseTag(ctx context.Context, arg DeleteCourseTagParams) (bool, error)
	DeleteDegreeCourse(ctx context.Context, arg DeleteDegreeCourseParams) (bool, error)
	DeleteDegreeType(ctx context.Context, id int64) (bool, error)
	DeleteStudent(ctx context.Context, id int64) (bool, error)
	DeleteStudentCourse(ctx context.Context, arg DeleteStudentCourseParams) (bool, error)
	DeleteTag(ctx context.Context, id int64) (bool, error)
	GetCourse(ctx context.Context, id int64) (Course, error)
	GetCourseByIds(ctx context.Context, courseIds []int64) ([]Course, error)
	GetCourseByName(ctx context.Context, courseName string) ([]Course, error)
	GetCourseQuestion(ctx context.Context, id int64) (CourseQuestion, error)
	GetCourseQuestionsByCourseId(ctx context.Context, courseID int64) ([]CourseQuestion, error)
	GetCoursesByDegreeId(ctx context.Context, id int64) ([]GetCoursesByDegreeIdRow, error)
	GetCoursesByStudentId(ctx context.Context, id int64) ([]GetCoursesByStudentIdRow, error)
	GetCoursesByTagId(ctx context.Context, id int64) ([]GetCoursesByTagIdRow, error)
	GetDegreeType(ctx context.Context, id int64) (DegreeType, error)
	GetDegreeTypeByName(ctx context.Context, degreeName string) ([]DegreeType, error)
	GetDegreesByCourseId(ctx context.Context, id int64) ([]GetDegreesByCourseIdRow, error)
	GetStudent(ctx context.Context, id int64) (GetStudentRow, error)
	GetStudentByUsername(ctx context.Context, arg GetStudentByUsernameParams) (GetStudentByUsernameRow, error)
	GetStudentsByCourseId(ctx context.Context, id int64) ([]GetStudentsByCourseIdRow, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, tagName string) ([]Tag, error)
	GetTagsByCourseId(ctx context.Context, id int64) ([]GetTagsByCourseIdRow, error)
	ListCourseQuestions(ctx context.Context) ([]CourseQuestion, error)
	ListCourses(ctx context.Context) ([]Course, error)
	ListDegreeTypes(ctx context.Context) ([]DegreeType, error)
	ListStudents(ctx context.Context) ([]ListStudentsRow, error)
	ListTags(ctx context.Context) ([]Tag, error)
	LoadRecommenderData(ctx context.Context) ([]LoadRecommenderDataRow, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateCourseQuestion(ctx context.Context, arg UpdateCourseQuestionParams) (CourseQuestion, error)
	UpdateDegreeType(ctx context.Context, arg UpdateDegreeTypeParams) (DegreeType, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (UpdateStudentRow, error)
	UpdateStudentCourse(ctx context.Context, arg UpdateStudentCourseParams) (StudentCourse, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
