// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: student.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO
    student (student_username, student_password)
VALUES
    ($1, $2)
RETURNING
    id,
    student_username
`

type CreateStudentParams struct {
	StudentUsername string `json:"student_username"`
	StudentPassword string `json:"student_password"`
}

type CreateStudentRow struct {
	ID              int64  `json:"id"`
	StudentUsername string `json:"student_username"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (CreateStudentRow, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.StudentUsername, arg.StudentPassword)
	var i CreateStudentRow
	err := row.Scan(&i.ID, &i.StudentUsername)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :one
DELETE FROM student
WHERE
    id = $1
RETURNING
    TRUE
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, deleteStudent, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getStudent = `-- name: GetStudent :one
SELECT
    id,
    student_username
FROM
    student
WHERE
    id = $1
`

type GetStudentRow struct {
	ID              int64  `json:"id"`
	StudentUsername string `json:"student_username"`
}

func (q *Queries) GetStudent(ctx context.Context, id int64) (GetStudentRow, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i GetStudentRow
	err := row.Scan(&i.ID, &i.StudentUsername)
	return i, err
}

const getStudentByUsername = `-- name: GetStudentByUsername :one
SELECT
    id,
    student_username
FROM
    student
WHERE
    student_username = $1
    AND student_password = $2
`

type GetStudentByUsernameParams struct {
	StudentUsername string `json:"student_username"`
	StudentPassword string `json:"student_password"`
}

type GetStudentByUsernameRow struct {
	ID              int64  `json:"id"`
	StudentUsername string `json:"student_username"`
}

func (q *Queries) GetStudentByUsername(ctx context.Context, arg GetStudentByUsernameParams) (GetStudentByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getStudentByUsername, arg.StudentUsername, arg.StudentPassword)
	var i GetStudentByUsernameRow
	err := row.Scan(&i.ID, &i.StudentUsername)
	return i, err
}

const getStudentByUsernameOnly = `-- name: GetStudentByUsernameOnly :one
SELECT
    id, student_username, student_password
FROM
    student
WHERE
    student_username = $1
`

func (q *Queries) GetStudentByUsernameOnly(ctx context.Context, studentUsername string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUsernameOnly, studentUsername)
	var i Student
	err := row.Scan(&i.ID, &i.StudentUsername, &i.StudentPassword)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT
    id,
    student_username
FROM
    student
`

type ListStudentsRow struct {
	ID              int64  `json:"id"`
	StudentUsername string `json:"student_username"`
}

func (q *Queries) ListStudents(ctx context.Context) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsRow
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(&i.ID, &i.StudentUsername); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE student
SET
    student_username = COALESCE($2, student_username),
    student_password = COALESCE($3, student_password)
WHERE
    id = $1
RETURNING
    id,
    student_username
`

type UpdateStudentParams struct {
	ID              int64       `json:"id"`
	StudentUsername pgtype.Text `json:"student_username"`
	StudentPassword pgtype.Text `json:"student_password"`
}

type UpdateStudentRow struct {
	ID              int64  `json:"id"`
	StudentUsername string `json:"student_username"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (UpdateStudentRow, error) {
	row := q.db.QueryRow(ctx, updateStudent, arg.ID, arg.StudentUsername, arg.StudentPassword)
	var i UpdateStudentRow
	err := row.Scan(&i.ID, &i.StudentUsername)
	return i, err
}
