// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: student_course.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudentCourse = `-- name: CreateStudentCourse :one
INSERT INTO
    student_course (student_id, course_id)
VALUES
    ($1, $2)
RETURNING
    student_id, course_id, marks, feedback
`

type CreateStudentCourseParams struct {
	StudentID int64 `json:"student_id"`
	CourseID  int64 `json:"course_id"`
}

func (q *Queries) CreateStudentCourse(ctx context.Context, arg CreateStudentCourseParams) (StudentCourse, error) {
	row := q.db.QueryRow(ctx, createStudentCourse, arg.StudentID, arg.CourseID)
	var i StudentCourse
	err := row.Scan(
		&i.StudentID,
		&i.CourseID,
		&i.Marks,
		&i.Feedback,
	)
	return i, err
}

const deleteStudentCourse = `-- name: DeleteStudentCourse :one
DELETE FROM student_course
WHERE
    course_id = $1
    AND student_id = $2
RETURNING
    TRUE
`

type DeleteStudentCourseParams struct {
	CourseID  int64 `json:"course_id"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) DeleteStudentCourse(ctx context.Context, arg DeleteStudentCourseParams) (bool, error) {
	row := q.db.QueryRow(ctx, deleteStudentCourse, arg.CourseID, arg.StudentID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getCoursesByStudentId = `-- name: GetCoursesByStudentId :many
SELECT
    course.id, course.course_name, course.difficulty
FROM
    student_course
    LEFT JOIN course ON course.id = student_course.course_id
    LEFT JOIN student ON student.id = student_course.student_id
WHERE
    student.id = $1
`

type GetCoursesByStudentIdRow struct {
	Course Course `json:"course"`
}

func (q *Queries) GetCoursesByStudentId(ctx context.Context, id int64) ([]GetCoursesByStudentIdRow, error) {
	rows, err := q.db.Query(ctx, getCoursesByStudentId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesByStudentIdRow
	for rows.Next() {
		var i GetCoursesByStudentIdRow
		if err := rows.Scan(&i.Course.ID, &i.Course.CourseName, &i.Course.Difficulty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentsByCourseId = `-- name: GetStudentsByCourseId :many
SELECT
    student.id, student.student_username, student.student_password
FROM
    student_course
    LEFT JOIN course ON course.id = student_course.course_id
    LEFT JOIN student ON student.id = student_course.student_id
WHERE
    course.id = $1
`

type GetStudentsByCourseIdRow struct {
	Student Student `json:"student"`
}

func (q *Queries) GetStudentsByCourseId(ctx context.Context, id int64) ([]GetStudentsByCourseIdRow, error) {
	rows, err := q.db.Query(ctx, getStudentsByCourseId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentsByCourseIdRow
	for rows.Next() {
		var i GetStudentsByCourseIdRow
		if err := rows.Scan(&i.Student.ID, &i.Student.StudentUsername, &i.Student.StudentPassword); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentCourse = `-- name: UpdateStudentCourse :one
UPDATE student_course
SET
    marks = $3,
    feedback = $4
WHERE
    student_id = $1
    AND course_id = $2
RETURNING
    student_id, course_id, marks, feedback
`

type UpdateStudentCourseParams struct {
	StudentID int64       `json:"student_id"`
	CourseID  int64       `json:"course_id"`
	Marks     pgtype.Int2 `json:"marks"`
	Feedback  pgtype.Bool `json:"feedback"`
}

func (q *Queries) UpdateStudentCourse(ctx context.Context, arg UpdateStudentCourseParams) (StudentCourse, error) {
	row := q.db.QueryRow(ctx, updateStudentCourse,
		arg.StudentID,
		arg.CourseID,
		arg.Marks,
		arg.Feedback,
	)
	var i StudentCourse
	err := row.Scan(
		&i.StudentID,
		&i.CourseID,
		&i.Marks,
		&i.Feedback,
	)
	return i, err
}
